from rest_framework import generics, permissions, status
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import Conversation
from .serializers import AskSerializer, ConversationSerializer
from .tasks import generate_response


class ConversationListView(generics.ListCreateAPIView):
    serializer_class = ConversationSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return Conversation.objects.filter(user=self.request.user)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class ConversationDetailView(generics.RetrieveAPIView):
    serializer_class = ConversationSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return Conversation.objects.filter(user=self.request.user)


class AskView(APIView):
    permission_classes = [permissions.IsAuthenticated]

    def post(self, request):
        serializer = AskSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        question = serializer.validated_data["question"]
        language = serializer.validated_data.get("language", request.user.preferred_language)
        conversation_id = serializer.validated_data.get("conversation_id")

        # Get or create conversation
        if conversation_id:
            try:
                conversation = Conversation.objects.get(id=conversation_id, user=request.user)
            except Conversation.DoesNotExist:
                return Response({"detail": "Conversation not found."}, status=404)
        else:
            conversation = Conversation.objects.create(
                user=request.user,
                language=language,
                tax_year=request.user.tax_year,
            )

        # Dispatch async task — response is generated by Celery worker
        task = generate_response.delay(
            conversation_id=conversation.id,
            question=question,
            user_type=request.user.user_type,
            language=language,
        )

        return Response(
            {"task_id": task.id, "conversation_id": conversation.id},
            status=status.HTTP_202_ACCEPTED,
        )
