# Generated by Django 6.0.5 on 2026-05-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_daily_message_count_user_daily_message_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intake_profile',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
