# Generated by Django 6.0.5 on 2026-06-13 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_gdpr_anonymization_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountantListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('bio_nl', models.TextField(blank=True)),
                ('bio_en', models.TextField(blank=True)),
                ('bio_fa', models.TextField(blank=True)),
                ('specializations', models.JSONField(default=list, help_text='e.g. ["zzp", "expat", "dga"]')),
                ('languages', models.JSONField(default=list, help_text='e.g. ["nl", "en", "fa"]')),
                ('hourly_rate_display', models.CharField(blank=True, help_text='e.g. "€75–€95"', max_length=50)),
                ('accepts_new_clients', models.BooleanField(default=True)),
                ('calendly_url', models.URLField(blank=True)),
                ('verified_accountant', models.BooleanField(default=False, help_text='Admin-verified credential (AA/RA/RB designation confirmed)')),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accountant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accountant_listings',
                'ordering': ['-rating', '-review_count'],
            },
        ),
        migrations.CreateModel(
            name='AccountantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin moderation required')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountant_reviews_approved', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.accountantlisting')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountant_reviews_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accountant_reviews',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(help_text='Preserved even if user is later anonymized', max_length=254)),
                ('request_type', models.CharField(choices=[('access', 'Access (Art. 15)'), ('deletion', 'Deletion (Art. 17)'), ('portability', 'Portability (Art. 20)')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('export_url', models.URLField(blank=True, help_text='Presigned URL for data export')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, help_text='submitted_at + 30 days', null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsar_requests_fulfilled', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsar_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_subject_requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('rollout_percentage', models.PositiveIntegerField(default=0, help_text='0=off, 100=all users. Intermediate values enable canary rollout.')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_flags_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feature_flags',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('document_uploaded', 'Document uploaded'), ('document_approved', 'Document approved'), ('document_rejected', 'Document rejected'), ('message_received', 'New message'), ('invitation_sent', 'Invitation sent'), ('invitation_accepted', 'Invitation accepted'), ('readiness_milestone', 'Readiness milestone'), ('engagement_ready', 'Engagement ready to file'), ('checklist_update', 'Checklist update'), ('system', 'System notification')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, help_text='Frontend route for deep link', max_length=500)),
                ('metadata', models.JSONField(blank=True, help_text='Extra context (engagement_id, doc_id, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx')],
            },
        ),
    ]
