# Generated by Django 5.2.15 on 2026-07-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_taxreminder_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountantlisting',
            name='specializations',
            field=models.JSONField(default=list, help_text='ZZP niche tags: e.g. ["it_tech", "creative_media", "consulting", "trades_construction", "healthcare_wellness", "international", "other"]'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('document_uploaded', 'Document uploaded'), ('document_approved', 'Document approved'), ('document_rejected', 'Document rejected'), ('message_received', 'New message'), ('invitation_sent', 'Invitation sent'), ('invitation_accepted', 'Invitation accepted'), ('readiness_milestone', 'Readiness milestone'), ('engagement_ready', 'Engagement ready to file'), ('checklist_update', 'Checklist update'), ('invitation_declined', 'Invitation declined'), ('system', 'System notification')], max_length=50),
        ),
        migrations.AlterField(
            model_name='taxreminder',
            name='category',
            field=models.CharField(choices=[('income_tax', 'Income Tax'), ('vat', 'VAT / BTW'), ('toeslagen', 'Toeslagen'), ('provisional_assessment', 'Voorlopige Aanslag'), ('box3', 'Box 3'), ('admin', 'Admin'), ('documents', 'Documents'), ('zzp_admin', 'ZZP Admin')], max_length=30),
        ),
    ]
