from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    USER_TYPES = [
        ("zzp", "ZZP / Freelancer"),
        ("employee", "Employee"),
        ("expat", "Expat"),
        ("dga", "DGA / Director"),
    ]

    LANGUAGES = [
        ("nl", "Nederlands"),
        ("en", "English"),
        ("fa", "فارسی"),
    ]

    PLANS = [("free", "Free"), ("premium", "Premium")]

    user_type = models.CharField(max_length=20, choices=USER_TYPES, blank=True)
    preferred_language = models.CharField(max_length=5, choices=LANGUAGES, default="nl")
    tax_year = models.PositiveIntegerField(default=2026)

    plan = models.CharField(max_length=20, choices=PLANS, default="free")
    stripe_customer_id = models.CharField(max_length=100, blank=True, default="")
    daily_message_count = models.PositiveIntegerField(default=0)
    daily_message_date = models.DateField(null=True, blank=True)

    # Tax profile collected via chat intake or /intake form
    intake_profile = models.JSONField(null=True, blank=True)

    # IB Guide + Simulation progress (server-persisted for authenticated users)
    ib_guide_answers    = models.JSONField(null=True, blank=True)
    simulation_state    = models.JSONField(null=True, blank=True)  # { answers, stepIdx }

    class Meta:
        db_table = "users"


class NotificationPreference(models.Model):
    """
    Smart Calendar / Reminder Engine — user notification preferences.

    Architecture designed for extensibility:
      in-app (now) → email (phase A) → WhatsApp (phase B) → SMS / calendar sync (phase C)

    Each channel is an opt-in boolean. The scheduler (Celery beat / Django-Q / APScheduler)
    reads these preferences to determine which users receive which reminders.

    Reminder types generated by the scheduler (NOT stored here — generated dynamically):
      deadline_btw_q*   — 7 days before each BTW quarter
      deadline_ib       — 14 days before IB return deadline
      reserve_monthly   — 1st of each month: "set aside €X this month"
      rule_change       — when a TaxRule is updated and user_type matches

    To add email: set email_enabled=True + implement send_reminder_email() in tasks.py
    To add WhatsApp: set whatsapp_enabled=True + implement whatsapp_send() with Twilio
    To add calendar: set calendar_sync=True + implement ical_export() endpoint
    """
    user = models.OneToOneField(
        "users.User", on_delete=models.CASCADE, related_name="notification_prefs"
    )

    # In-app: always on for authenticated users (no opt-out needed for in-app)
    inapp_enabled   = models.BooleanField(default=True)

    # Email reminders (Phase A — requires SMTP config)
    email_enabled   = models.BooleanField(default=False)
    email_btw       = models.BooleanField(default=True)
    email_ib        = models.BooleanField(default=True)
    email_reserve   = models.BooleanField(default=False)
    email_rule_change = models.BooleanField(default=True)

    # Future channels (Phase B / C — set to False until implemented)
    whatsapp_enabled = models.BooleanField(default=False)
    sms_enabled      = models.BooleanField(default=False)
    calendar_sync    = models.BooleanField(default=False)

    # Scheduling preferences
    reminder_lead_days = models.PositiveIntegerField(default=7)  # how many days before deadline

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "notification_preferences"

    def __str__(self):
        channels = [c for c, v in [("email", self.email_enabled), ("WhatsApp", self.whatsapp_enabled), ("SMS", self.sms_enabled)] if v]
        return f"{self.user_id} — {', '.join(channels) or 'in-app only'}"


class TaxYearSnapshot(models.Model):
    """
    Future Memory Foundation — captures a user's complete tax profile + result
    at the end of each tax year so the platform can:
      - show multi-year tax history
      - compare year-over-year changes
      - carry over unchanged fields (partner, children, Box 3)
      - detect anomalies (income dropped 40% → flag for review)
      - support accountant review workflows

    A snapshot is created automatically when:
      - The user files their IB return (detected via chat/simulation completion)
      - An admin triggers year-end archival
      - The user explicitly saves a "year-end snapshot"

    Design notes:
      - `profile_snapshot` mirrors `intake_profile` JSON at time of capture
      - `calc_snapshot` mirrors the calculator engine output JSON
      - `source` tracks how the snapshot was created for audit purposes
      - `is_final` distinguishes working estimates from filed/confirmed values
    """
    SOURCE_CHOICES = [
        ("auto",      "Auto-captured"),
        ("ib_guide",  "IB Guide completion"),
        ("simulation","Simulation completion"),
        ("admin",     "Admin-triggered"),
        ("user",      "User-saved"),
    ]

    user = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="year_snapshots"
    )
    tax_year = models.PositiveIntegerField()
    profile_snapshot = models.JSONField()
    calc_snapshot    = models.JSONField(null=True, blank=True)
    source           = models.CharField(max_length=20, choices=SOURCE_CHOICES, default="auto")
    is_final         = models.BooleanField(default=False)
    notes            = models.TextField(blank=True)
    created_at       = models.DateTimeField(auto_now_add=True)
    updated_at       = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "tax_year_snapshots"
        unique_together = [("user", "tax_year", "is_final")]
        ordering = ["-tax_year"]

    def __str__(self):
        return f"{self.user_id} / {self.tax_year} ({'final' if self.is_final else 'draft'})"
