from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    USER_TYPES = [
        ("zzp", "ZZP / Freelancer"),
        ("employee", "Employee"),
        ("expat", "Expat"),
        ("dga", "DGA / Director"),
    ]

    LANGUAGES = [
        ("nl", "Nederlands"),
        ("en", "English"),
        ("fa", "فارسی"),
    ]

    PLANS = [("free", "Free"), ("premium", "Premium")]

    ROLES = [
        ("client",     "Client"),
        ("accountant", "Accountant"),
        ("admin",      "Admin"),
    ]

    user_type = models.CharField(max_length=20, choices=USER_TYPES, blank=True)
    role      = models.CharField(max_length=20, choices=ROLES, default="client")
    preferred_language = models.CharField(max_length=5, choices=LANGUAGES, default="nl")
    tax_year = models.PositiveIntegerField(default=2026)

    plan = models.CharField(max_length=20, choices=PLANS, default="free")
    stripe_customer_id = models.CharField(max_length=100, blank=True, default="")
    daily_message_count = models.PositiveIntegerField(default=0)
    daily_message_date = models.DateField(null=True, blank=True)

    # Tax profile collected via chat intake or /intake form
    intake_profile = models.JSONField(null=True, blank=True)

    # IB Guide + Simulation progress (server-persisted for authenticated users)
    ib_guide_answers    = models.JSONField(null=True, blank=True)
    simulation_state    = models.JSONField(null=True, blank=True)  # { answers, stepIdx }

    # AI Tax Memory — injected into Claude system prompt for paid/logged-in users
    # Keys: user_type, income, hours_worked, known_deductions, last_calc_result, open_questions
    tax_memory          = models.JSONField(null=True, blank=True)

    # Google Calendar push sync
    google_calendar_enabled       = models.BooleanField(default=False)
    google_calendar_refresh_token = models.TextField(null=True, blank=True)

    # GDPR fields
    deletion_requested_at = models.DateTimeField(null=True, blank=True)
    anonymized_at         = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "users"

    def anonymize(self):
        """
        GDPR anonymization stub.
        Erases all PII fields and marks the account as anonymized.
        Actual deletion of linked data is handled by cascade deletes.
        """
        from django.utils import timezone
        self.first_name                    = ""
        self.last_name                     = ""
        self.email                         = f"deleted_{self.pk}@anonymized.invalid"
        self.username                      = f"deleted_{self.pk}"
        self.intake_profile                = None
        self.tax_memory                    = None
        self.ib_guide_answers              = None
        self.simulation_state              = None
        self.google_calendar_refresh_token = None
        self.google_calendar_enabled       = False
        self.is_active                     = False
        self.anonymized_at                 = timezone.now()
        self.save(update_fields=[
            "first_name", "last_name", "email", "username",
            "intake_profile", "tax_memory", "ib_guide_answers",
            "simulation_state", "google_calendar_refresh_token",
            "google_calendar_enabled", "is_active", "anonymized_at",
        ])


class NotificationPreference(models.Model):
    """
    Smart Calendar / Reminder Engine — user notification preferences.

    Architecture designed for extensibility:
      in-app (now) → email (phase A) → WhatsApp (phase B) → SMS / calendar sync (phase C)

    Each channel is an opt-in boolean. The scheduler (Celery beat / Django-Q / APScheduler)
    reads these preferences to determine which users receive which reminders.

    Reminder types generated by the scheduler (NOT stored here — generated dynamically):
      deadline_btw_q*   — 7 days before each BTW quarter
      deadline_ib       — 14 days before IB return deadline
      reserve_monthly   — 1st of each month: "set aside €X this month"
      rule_change       — when a TaxRule is updated and user_type matches

    To add email: set email_enabled=True + implement send_reminder_email() in tasks.py
    To add WhatsApp: set whatsapp_enabled=True + implement whatsapp_send() with Twilio
    To add calendar: set calendar_sync=True + implement ical_export() endpoint
    """
    user = models.OneToOneField(
        "users.User", on_delete=models.CASCADE, related_name="notification_prefs"
    )

    # In-app: always on for authenticated users (no opt-out needed for in-app)
    inapp_enabled   = models.BooleanField(default=True)

    # Email reminders (Phase A — requires SMTP config)
    email_enabled   = models.BooleanField(default=False)
    email_btw       = models.BooleanField(default=True)
    email_ib        = models.BooleanField(default=True)
    email_reserve   = models.BooleanField(default=False)
    email_rule_change = models.BooleanField(default=True)

    # Future channels (Phase B / C — set to False until implemented)
    whatsapp_enabled = models.BooleanField(default=False)
    sms_enabled      = models.BooleanField(default=False)
    calendar_sync    = models.BooleanField(default=False)

    # Scheduling preferences
    reminder_lead_days = models.PositiveIntegerField(default=7)  # how many days before deadline

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "notification_preferences"

    def __str__(self):
        channels = [c for c, v in [("email", self.email_enabled), ("WhatsApp", self.whatsapp_enabled), ("SMS", self.sms_enabled)] if v]
        return f"{self.user_id} — {', '.join(channels) or 'in-app only'}"


class TaxYearSnapshot(models.Model):
    """
    Future Memory Foundation — captures a user's complete tax profile + result
    at the end of each tax year so the platform can:
      - show multi-year tax history
      - compare year-over-year changes
      - carry over unchanged fields (partner, children, Box 3)
      - detect anomalies (income dropped 40% → flag for review)
      - support accountant review workflows

    A snapshot is created automatically when:
      - The user files their IB return (detected via chat/simulation completion)
      - An admin triggers year-end archival
      - The user explicitly saves a "year-end snapshot"

    Design notes:
      - `profile_snapshot` mirrors `intake_profile` JSON at time of capture
      - `calc_snapshot` mirrors the calculator engine output JSON
      - `source` tracks how the snapshot was created for audit purposes
      - `is_final` distinguishes working estimates from filed/confirmed values
    """
    SOURCE_CHOICES = [
        ("auto",      "Auto-captured"),
        ("ib_guide",  "IB Guide completion"),
        ("simulation","Simulation completion"),
        ("admin",     "Admin-triggered"),
        ("user",      "User-saved"),
    ]

    user = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="year_snapshots"
    )
    tax_year = models.PositiveIntegerField()
    profile_snapshot = models.JSONField()
    calc_snapshot    = models.JSONField(null=True, blank=True)
    source           = models.CharField(max_length=20, choices=SOURCE_CHOICES, default="auto")
    is_final         = models.BooleanField(default=False)
    notes            = models.TextField(blank=True)
    created_at       = models.DateTimeField(auto_now_add=True)
    updated_at       = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "tax_year_snapshots"
        unique_together = [("user", "tax_year", "is_final")]
        ordering = ["-tax_year"]

    def __str__(self):
        return f"{self.user_id} / {self.tax_year} ({'final' if self.is_final else 'draft'})"


class AccountantProfile(models.Model):
    """B2B tier — accountants who manage multiple client accounts."""

    DESIGNATION_CHOICES = [
        ("RB",    "Register Belastingadviseur (RB)"),
        ("AA",    "Accountant-Administratieconsulent (AA)"),
        ("RA",    "Registeraccountant (RA)"),
        ("other", "Other"),
    ]

    user         = models.OneToOneField("users.User", on_delete=models.CASCADE, related_name="accountant_profile")
    firm_name    = models.CharField(max_length=200, blank=True)
    kvk_number   = models.CharField(max_length=20, blank=True, help_text="8-digit KvK registration number")
    designation  = models.CharField(max_length=10, choices=DESIGNATION_CHOICES, blank=True)
    phone        = models.CharField(max_length=30, blank=True)
    client_limit = models.PositiveIntegerField(default=10)
    is_verified  = models.BooleanField(default=False, help_text="Admin-verified accountant credential")
    created_at   = models.DateTimeField(auto_now_add=True)
    updated_at   = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "accountant_profiles"

    def __str__(self):
        return f"{self.user_id} — {self.firm_name or 'Accountant'} ({self.get_designation_display()})"


class AccountantClient(models.Model):
    """Relationship between an accountant and a client user."""
    accountant = models.ForeignKey("users.AccountantProfile", on_delete=models.CASCADE, related_name="clients")
    client_user = models.ForeignKey("users.User", on_delete=models.CASCADE, related_name="accountant_links", null=True, blank=True)
    nickname = models.CharField(max_length=100, blank=True)
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "accountant_clients"

    def __str__(self):
        return f"{self.accountant_id} → {self.nickname or self.client_user_id}"


class AccountantInvitation(models.Model):
    """
    Accountant sends an invitation to a client by email.
    Client sees it in their dashboard and accepts or declines.
    On accept, an AccountantClient link is created automatically.
    """
    STATUS_CHOICES = [
        ("pending",   "Pending"),
        ("accepted",  "Accepted"),
        ("declined",  "Declined"),
        ("cancelled", "Cancelled"),
    ]

    accountant    = models.ForeignKey("users.AccountantProfile", on_delete=models.CASCADE, related_name="sent_invitations")
    invited_email = models.EmailField(help_text="Email address of the invited client")
    client_user   = models.ForeignKey(
        "users.User", null=True, blank=True,
        on_delete=models.SET_NULL, related_name="accountant_invitations",
    )
    message    = models.TextField(blank=True, help_text="Optional personal message from accountant")
    status     = models.CharField(max_length=20, choices=STATUS_CHOICES, default="pending")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "accountant_invitations"
        # Prevent duplicate pending invitations for the same email
        constraints = [
            models.UniqueConstraint(
                fields=["accountant", "invited_email"],
                condition=models.Q(status="pending"),
                name="unique_pending_invitation",
            )
        ]

    def __str__(self):
        return f"{self.accountant_id} → {self.invited_email} [{self.status}]"


class PushSubscription(models.Model):
    """
    Web Push API subscription — one per browser/device per user.
    The endpoint + keys are provided by the browser when the user grants
    notification permission. Stored server-side to allow sending pushes
    from backend events (invitation sent, accepted, etc.).

    Expired/gone subscriptions (HTTP 404/410 from push service) are
    automatically deleted when a push fails.
    """
    user       = models.ForeignKey("users.User", on_delete=models.CASCADE, related_name="push_subscriptions")
    endpoint   = models.TextField(unique=True)
    p256dh     = models.TextField(help_text="Public key (base64url)")
    auth       = models.TextField(help_text="Auth secret (base64url)")
    user_agent = models.CharField(max_length=300, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "push_subscriptions"

    def __str__(self):
        return f"{self.user_id} — {self.endpoint[:60]}…"


class EmailCapture(models.Model):
    """Anonymous email captures from landing page and deduction checker."""
    email = models.EmailField()
    user_type = models.CharField(max_length=20, blank=True)
    source_page = models.CharField(max_length=80, default="landing")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "email_captures"

    def __str__(self):
        return f"{self.email} ({self.source_page})"


class TaxReminder(models.Model):
    """
    Smart Calendar / Reminder Engine — a single tax event / deadline.

    Covers all 21 reminder categories from the spec:
    income_tax, vat, payroll, corporate_tax, dividend_tax, toeslagen,
    provisional_assessment, box3, expat, admin, documents, zzp_admin.

    Seeded via management command seed_reminders. Admin can add/edit.
    Frontend reads via GET /api/users/reminders/.
    """
    CATEGORY_CHOICES = [
        ("income_tax",            "Income Tax"),
        ("vat",                   "VAT / BTW"),
        ("payroll",               "Payroll"),
        ("corporate_tax",         "Corporate Tax"),
        ("dividend_tax",          "Dividend Tax"),
        ("toeslagen",             "Toeslagen"),
        ("provisional_assessment","Voorlopige Aanslag"),
        ("box3",                  "Box 3"),
        ("expat",                 "Expat"),
        ("admin",                 "Admin"),
        ("documents",             "Documents"),
        ("zzp_admin",             "ZZP Admin"),
        ("dga",                   "DGA"),
    ]
    SOURCE_STATUS_CHOICES = [
        ("official",     "Official Belastingdienst source"),
        ("estimated",    "Estimated / typical date"),
        ("user_defined", "User-defined"),
    ]
    ACTION_TYPE_CHOICES = [
        ("file_return",        "File return"),
        ("pay_tax",            "Pay tax"),
        ("update_income",      "Update income estimate"),
        ("upload_document",    "Upload document"),
        ("check_eligibility",  "Check eligibility"),
        ("review_rule",        "Review rule"),
        ("book_consultation",  "Book consultation"),
        ("log_hours",          "Log hours"),
        ("log_expenses",       "Log expenses"),
        ("review_deadline",    "Review deadline"),
    ]
    VERIFICATION_CHOICES = [
        ("draft",          "Draft"),
        ("pending_review", "Pending review"),
        ("verified",       "Verified"),
        ("expired",        "Expired"),
    ]
    RECURRENCE_CHOICES = [
        ("monthly",   "Monthly"),
        ("quarterly", "Quarterly"),
        ("yearly",    "Yearly"),
        ("custom",    "Custom"),
    ]

    title_nl = models.CharField(max_length=200)
    title_en = models.CharField(max_length=200)
    title_fa = models.CharField(max_length=200)
    description_nl = models.TextField(blank=True)
    description_en = models.TextField(blank=True)
    description_fa = models.TextField(blank=True)

    category   = models.CharField(max_length=30, choices=CATEGORY_CHOICES)
    user_types = models.JSONField(default=list)  # ["zzp"], ["employee","expat"], etc.

    tax_year = models.PositiveIntegerField(default=2026)
    due_date = models.DateField()
    recurrence = models.CharField(max_length=20, choices=RECURRENCE_CHOICES, null=True, blank=True)
    reminder_offsets = models.JSONField(default=list)  # [30, 14, 7, 1] days before due_date

    source_url    = models.URLField(blank=True)
    source_status = models.CharField(max_length=20, choices=SOURCE_STATUS_CHOICES, default="official")

    verification_status = models.CharField(max_length=20, choices=VERIFICATION_CHOICES, default="verified")
    action_type         = models.CharField(max_length=30, choices=ACTION_TYPE_CHOICES, default="review_deadline")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "tax_reminders"
        ordering = ["due_date"]

    def __str__(self):
        return f"{self.title_en} ({self.due_date})"

    def title(self, lang: str) -> str:
        return getattr(self, f"title_{lang}", self.title_en) or self.title_en

    def description(self, lang: str) -> str:
        return getattr(self, f"description_{lang}", self.description_en) or self.description_en


class FeatureFlag(models.Model):
    """
    Platform-wide feature flags for controlled rollout.
    Toggled by admins via the admin console.
    """
    key = models.CharField(max_length=100, unique=True)
    is_enabled = models.BooleanField(default=False)
    rollout_percentage = models.PositiveIntegerField(
        default=0,
        help_text="0=off, 100=all users. Intermediate values enable canary rollout."
    )
    description = models.TextField(blank=True)
    updated_by = models.ForeignKey(
        "users.User", on_delete=models.SET_NULL, null=True, blank=True,
        related_name="feature_flags_updated"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "feature_flags"
        ordering = ["key"]

    def __str__(self):
        return f"{self.key} = {'on' if self.is_enabled else 'off'} ({self.rollout_percentage}%)"


class DataSubjectRequest(models.Model):
    """
    GDPR Data Subject Request (DSAR) — access, deletion, or portability.
    Must be fulfilled within 30 days (GDPR Art. 15).
    """
    REQUEST_TYPE_CHOICES = [
        ("access", "Access (Art. 15)"),
        ("deletion", "Deletion (Art. 17)"),
        ("portability", "Portability (Art. 20)"),
    ]
    STATUS_CHOICES = [
        ("open", "Open"),
        ("in_progress", "In Progress"),
        ("fulfilled", "Fulfilled"),
        ("rejected", "Rejected"),
    ]

    user = models.ForeignKey(
        "users.User", on_delete=models.SET_NULL, null=True, blank=True,
        related_name="dsar_requests"
    )
    user_email = models.EmailField(help_text="Preserved even if user is later anonymized")
    request_type = models.CharField(max_length=20, choices=REQUEST_TYPE_CHOICES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="open")
    notes = models.TextField(blank=True)
    export_url = models.URLField(blank=True, help_text="Presigned URL for data export")
    fulfilled_by = models.ForeignKey(
        "users.User", on_delete=models.SET_NULL, null=True, blank=True,
        related_name="dsar_requests_fulfilled"
    )
    submitted_at = models.DateTimeField(auto_now_add=True)
    due_date = models.DateTimeField(null=True, blank=True, help_text="submitted_at + 30 days")
    fulfilled_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "data_subject_requests"
        ordering = ["-submitted_at"]

    def __str__(self):
        return f"DSAR {self.request_type} — {self.user_email} ({self.status})"


class Notification(models.Model):
    """
    In-app notification record. Shown in the notification bell.
    Push and email are separate channels; this is the in-app record.
    """
    NOTIFICATION_TYPE_CHOICES = [
        ("document_uploaded", "Document uploaded"),
        ("document_approved", "Document approved"),
        ("document_rejected", "Document rejected"),
        ("message_received", "New message"),
        ("invitation_sent", "Invitation sent"),
        ("invitation_accepted", "Invitation accepted"),
        ("readiness_milestone", "Readiness milestone"),
        ("engagement_ready", "Engagement ready to file"),
        ("checklist_update", "Checklist update"),
        ("system", "System notification"),
    ]

    user = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="notifications"
    )
    notification_type = models.CharField(max_length=50, choices=NOTIFICATION_TYPE_CHOICES)
    title = models.CharField(max_length=200)
    body = models.TextField(blank=True)
    is_read = models.BooleanField(default=False)
    read_at = models.DateTimeField(null=True, blank=True)
    action_url = models.CharField(max_length=500, blank=True, help_text="Frontend route for deep link")
    metadata = models.JSONField(null=True, blank=True, help_text="Extra context (engagement_id, doc_id, etc.)")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "notifications"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["user", "is_read", "-created_at"]),
        ]

    def __str__(self):
        return f"{self.notification_type} → {self.user_id} ({'read' if self.is_read else 'unread'})"


class AccountantListing(models.Model):
    """
    Marketplace listing for an accountant.
    Opt-in: accountants explicitly create a listing to appear in the directory.
    """
    accountant = models.OneToOneField(
        "users.User", on_delete=models.CASCADE, related_name="marketplace_listing"
    )
    display_name = models.CharField(max_length=200)
    bio_nl = models.TextField(blank=True)
    bio_en = models.TextField(blank=True)
    bio_fa = models.TextField(blank=True)
    specializations = models.JSONField(
        default=list,
        help_text='e.g. ["zzp", "expat", "dga"]'
    )
    languages = models.JSONField(
        default=list,
        help_text='e.g. ["nl", "en", "fa"]'
    )
    hourly_rate_display = models.CharField(max_length=50, blank=True, help_text='e.g. "€75–€95"')
    accepts_new_clients = models.BooleanField(default=True)
    calendly_url = models.URLField(blank=True)
    verified_accountant = models.BooleanField(
        default=False,
        help_text="Admin-verified credential (AA/RA/RB designation confirmed)"
    )
    is_active = models.BooleanField(default=True)
    rating = models.FloatField(null=True, blank=True)
    review_count = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "accountant_listings"
        ordering = ["-rating", "-review_count"]

    def __str__(self):
        return f"{self.display_name} (marketplace)"


class AccountantReview(models.Model):
    """
    Client review of an accountant, posted after engagement is Filed.
    Moderated by admin before appearing publicly.
    """
    listing = models.ForeignKey(AccountantListing, on_delete=models.CASCADE, related_name="reviews")
    reviewer = models.ForeignKey(
        "users.User", on_delete=models.SET_NULL, null=True, blank=True,
        related_name="accountant_reviews_written"
    )
    rating = models.PositiveIntegerField()
    text = models.TextField(blank=True)
    is_anonymous = models.BooleanField(default=False)
    is_approved = models.BooleanField(default=False, help_text="Admin moderation required")
    approved_by = models.ForeignKey(
        "users.User", on_delete=models.SET_NULL, null=True, blank=True,
        related_name="accountant_reviews_approved"
    )
    submitted_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "accountant_reviews"
        ordering = ["-submitted_at"]

    def __str__(self):
        return f"Review {self.rating}/5 for {self.listing_id}"


class UserItemState(models.Model):
    """
    Persists per-user dismiss / snooze / done states for alerts and actions
    on the backend so states survive browser clears and device switches.

    Synced for authenticated users only; anonymous users continue to use
    localStorage (no account = no server state).
    """
    ITEM_TYPES = [("alert", "Alert"), ("action", "Action")]
    STATE_CHOICES = [
        ("open",      "Open"),
        ("done",      "Done"),
        ("dismissed", "Dismissed"),
        ("snoozed",   "Snoozed"),
    ]

    user         = models.ForeignKey("users.User", on_delete=models.CASCADE, related_name="item_states")
    item_type    = models.CharField(max_length=10, choices=ITEM_TYPES)
    item_id      = models.CharField(max_length=120)
    state        = models.CharField(max_length=20, choices=STATE_CHOICES, default="open")
    snoozed_until = models.DateField(null=True, blank=True)
    updated_at   = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "user_item_states"
        unique_together = [("user", "item_type", "item_id")]

    def __str__(self):
        return f"{self.user_id} / {self.item_type} / {self.item_id} → {self.state}"
