from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    USER_TYPES = [
        ("zzp", "ZZP / Freelancer"),
        ("employee", "Employee"),
        ("expat", "Expat"),
        ("dga", "DGA / Director"),
    ]

    LANGUAGES = [
        ("nl", "Nederlands"),
        ("en", "English"),
        ("fa", "فارسی"),
    ]

    PLANS = [("free", "Free"), ("premium", "Premium")]

    ROLES = [
        ("client",     "Client"),
        ("accountant", "Accountant"),
        ("admin",      "Admin"),
    ]

    user_type = models.CharField(max_length=20, choices=USER_TYPES, blank=True)
    role      = models.CharField(max_length=20, choices=ROLES, default="client")
    preferred_language = models.CharField(max_length=5, choices=LANGUAGES, default="nl")
    tax_year = models.PositiveIntegerField(default=2026)

    plan = models.CharField(max_length=20, choices=PLANS, default="free")
    stripe_customer_id = models.CharField(max_length=100, blank=True, default="")
    daily_message_count = models.PositiveIntegerField(default=0)
    daily_message_date = models.DateField(null=True, blank=True)

    # Tax profile collected via chat intake or /intake form
    intake_profile = models.JSONField(null=True, blank=True)

    # IB Guide + Simulation progress (server-persisted for authenticated users)
    ib_guide_answers    = models.JSONField(null=True, blank=True)
    simulation_state    = models.JSONField(null=True, blank=True)  # { answers, stepIdx }

    # AI Tax Memory — injected into Claude system prompt for paid/logged-in users
    # Keys: user_type, income, hours_worked, known_deductions, last_calc_result, open_questions
    tax_memory          = models.JSONField(null=True, blank=True)

    class Meta:
        db_table = "users"


class NotificationPreference(models.Model):
    """
    Smart Calendar / Reminder Engine — user notification preferences.

    Architecture designed for extensibility:
      in-app (now) → email (phase A) → WhatsApp (phase B) → SMS / calendar sync (phase C)

    Each channel is an opt-in boolean. The scheduler (Celery beat / Django-Q / APScheduler)
    reads these preferences to determine which users receive which reminders.

    Reminder types generated by the scheduler (NOT stored here — generated dynamically):
      deadline_btw_q*   — 7 days before each BTW quarter
      deadline_ib       — 14 days before IB return deadline
      reserve_monthly   — 1st of each month: "set aside €X this month"
      rule_change       — when a TaxRule is updated and user_type matches

    To add email: set email_enabled=True + implement send_reminder_email() in tasks.py
    To add WhatsApp: set whatsapp_enabled=True + implement whatsapp_send() with Twilio
    To add calendar: set calendar_sync=True + implement ical_export() endpoint
    """
    user = models.OneToOneField(
        "users.User", on_delete=models.CASCADE, related_name="notification_prefs"
    )

    # In-app: always on for authenticated users (no opt-out needed for in-app)
    inapp_enabled   = models.BooleanField(default=True)

    # Email reminders (Phase A — requires SMTP config)
    email_enabled   = models.BooleanField(default=False)
    email_btw       = models.BooleanField(default=True)
    email_ib        = models.BooleanField(default=True)
    email_reserve   = models.BooleanField(default=False)
    email_rule_change = models.BooleanField(default=True)

    # Future channels (Phase B / C — set to False until implemented)
    whatsapp_enabled = models.BooleanField(default=False)
    sms_enabled      = models.BooleanField(default=False)
    calendar_sync    = models.BooleanField(default=False)

    # Scheduling preferences
    reminder_lead_days = models.PositiveIntegerField(default=7)  # how many days before deadline

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "notification_preferences"

    def __str__(self):
        channels = [c for c, v in [("email", self.email_enabled), ("WhatsApp", self.whatsapp_enabled), ("SMS", self.sms_enabled)] if v]
        return f"{self.user_id} — {', '.join(channels) or 'in-app only'}"


class TaxYearSnapshot(models.Model):
    """
    Future Memory Foundation — captures a user's complete tax profile + result
    at the end of each tax year so the platform can:
      - show multi-year tax history
      - compare year-over-year changes
      - carry over unchanged fields (partner, children, Box 3)
      - detect anomalies (income dropped 40% → flag for review)
      - support accountant review workflows

    A snapshot is created automatically when:
      - The user files their IB return (detected via chat/simulation completion)
      - An admin triggers year-end archival
      - The user explicitly saves a "year-end snapshot"

    Design notes:
      - `profile_snapshot` mirrors `intake_profile` JSON at time of capture
      - `calc_snapshot` mirrors the calculator engine output JSON
      - `source` tracks how the snapshot was created for audit purposes
      - `is_final` distinguishes working estimates from filed/confirmed values
    """
    SOURCE_CHOICES = [
        ("auto",      "Auto-captured"),
        ("ib_guide",  "IB Guide completion"),
        ("simulation","Simulation completion"),
        ("admin",     "Admin-triggered"),
        ("user",      "User-saved"),
    ]

    user = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="year_snapshots"
    )
    tax_year = models.PositiveIntegerField()
    profile_snapshot = models.JSONField()
    calc_snapshot    = models.JSONField(null=True, blank=True)
    source           = models.CharField(max_length=20, choices=SOURCE_CHOICES, default="auto")
    is_final         = models.BooleanField(default=False)
    notes            = models.TextField(blank=True)
    created_at       = models.DateTimeField(auto_now_add=True)
    updated_at       = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "tax_year_snapshots"
        unique_together = [("user", "tax_year", "is_final")]
        ordering = ["-tax_year"]

    def __str__(self):
        return f"{self.user_id} / {self.tax_year} ({'final' if self.is_final else 'draft'})"


class AccountantProfile(models.Model):
    """B2B tier — accountants who manage multiple client accounts."""

    DESIGNATION_CHOICES = [
        ("RB",    "Register Belastingadviseur (RB)"),
        ("AA",    "Accountant-Administratieconsulent (AA)"),
        ("RA",    "Registeraccountant (RA)"),
        ("other", "Other"),
    ]

    user         = models.OneToOneField("users.User", on_delete=models.CASCADE, related_name="accountant_profile")
    firm_name    = models.CharField(max_length=200, blank=True)
    kvk_number   = models.CharField(max_length=20, blank=True, help_text="8-digit KvK registration number")
    designation  = models.CharField(max_length=10, choices=DESIGNATION_CHOICES, blank=True)
    phone        = models.CharField(max_length=30, blank=True)
    client_limit = models.PositiveIntegerField(default=10)
    is_verified  = models.BooleanField(default=False, help_text="Admin-verified accountant credential")
    created_at   = models.DateTimeField(auto_now_add=True)
    updated_at   = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "accountant_profiles"

    def __str__(self):
        return f"{self.user_id} — {self.firm_name or 'Accountant'} ({self.get_designation_display()})"


class AccountantClient(models.Model):
    """Relationship between an accountant and a client user."""
    accountant = models.ForeignKey("users.AccountantProfile", on_delete=models.CASCADE, related_name="clients")
    client_user = models.ForeignKey("users.User", on_delete=models.CASCADE, related_name="accountant_links", null=True, blank=True)
    nickname = models.CharField(max_length=100, blank=True)
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "accountant_clients"

    def __str__(self):
        return f"{self.accountant_id} → {self.nickname or self.client_user_id}"


class EmailCapture(models.Model):
    """Anonymous email captures from landing page and deduction checker."""
    email = models.EmailField()
    user_type = models.CharField(max_length=20, blank=True)
    source_page = models.CharField(max_length=80, default="landing")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "email_captures"

    def __str__(self):
        return f"{self.email} ({self.source_page})"


class TaxReminder(models.Model):
    """
    Smart Calendar / Reminder Engine — a single tax event / deadline.

    Covers all 21 reminder categories from the spec:
    income_tax, vat, payroll, corporate_tax, dividend_tax, toeslagen,
    provisional_assessment, box3, expat, admin, documents, zzp_admin.

    Seeded via management command seed_reminders. Admin can add/edit.
    Frontend reads via GET /api/users/reminders/.
    """
    CATEGORY_CHOICES = [
        ("income_tax",            "Income Tax"),
        ("vat",                   "VAT / BTW"),
        ("payroll",               "Payroll"),
        ("corporate_tax",         "Corporate Tax"),
        ("dividend_tax",          "Dividend Tax"),
        ("toeslagen",             "Toeslagen"),
        ("provisional_assessment","Voorlopige Aanslag"),
        ("box3",                  "Box 3"),
        ("expat",                 "Expat"),
        ("admin",                 "Admin"),
        ("documents",             "Documents"),
        ("zzp_admin",             "ZZP Admin"),
        ("dga",                   "DGA"),
    ]
    SOURCE_STATUS_CHOICES = [
        ("official",     "Official Belastingdienst source"),
        ("estimated",    "Estimated / typical date"),
        ("user_defined", "User-defined"),
    ]
    ACTION_TYPE_CHOICES = [
        ("file_return",        "File return"),
        ("pay_tax",            "Pay tax"),
        ("update_income",      "Update income estimate"),
        ("upload_document",    "Upload document"),
        ("check_eligibility",  "Check eligibility"),
        ("review_rule",        "Review rule"),
        ("book_consultation",  "Book consultation"),
        ("log_hours",          "Log hours"),
        ("log_expenses",       "Log expenses"),
        ("review_deadline",    "Review deadline"),
    ]
    VERIFICATION_CHOICES = [
        ("draft",          "Draft"),
        ("pending_review", "Pending review"),
        ("verified",       "Verified"),
        ("expired",        "Expired"),
    ]
    RECURRENCE_CHOICES = [
        ("monthly",   "Monthly"),
        ("quarterly", "Quarterly"),
        ("yearly",    "Yearly"),
        ("custom",    "Custom"),
    ]

    title_nl = models.CharField(max_length=200)
    title_en = models.CharField(max_length=200)
    title_fa = models.CharField(max_length=200)
    description_nl = models.TextField(blank=True)
    description_en = models.TextField(blank=True)
    description_fa = models.TextField(blank=True)

    category   = models.CharField(max_length=30, choices=CATEGORY_CHOICES)
    user_types = models.JSONField(default=list)  # ["zzp"], ["employee","expat"], etc.

    tax_year = models.PositiveIntegerField(default=2026)
    due_date = models.DateField()
    recurrence = models.CharField(max_length=20, choices=RECURRENCE_CHOICES, null=True, blank=True)
    reminder_offsets = models.JSONField(default=list)  # [30, 14, 7, 1] days before due_date

    source_url    = models.URLField(blank=True)
    source_status = models.CharField(max_length=20, choices=SOURCE_STATUS_CHOICES, default="official")

    verification_status = models.CharField(max_length=20, choices=VERIFICATION_CHOICES, default="verified")
    action_type         = models.CharField(max_length=30, choices=ACTION_TYPE_CHOICES, default="review_deadline")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "tax_reminders"
        ordering = ["due_date"]

    def __str__(self):
        return f"{self.title_en} ({self.due_date})"

    def title(self, lang: str) -> str:
        return getattr(self, f"title_{lang}", self.title_en) or self.title_en

    def description(self, lang: str) -> str:
        return getattr(self, f"description_{lang}", self.description_en) or self.description_en


class UserItemState(models.Model):
    """
    Persists per-user dismiss / snooze / done states for alerts and actions
    on the backend so states survive browser clears and device switches.

    Synced for authenticated users only; anonymous users continue to use
    localStorage (no account = no server state).
    """
    ITEM_TYPES = [("alert", "Alert"), ("action", "Action")]
    STATE_CHOICES = [
        ("open",      "Open"),
        ("done",      "Done"),
        ("dismissed", "Dismissed"),
        ("snoozed",   "Snoozed"),
    ]

    user         = models.ForeignKey("users.User", on_delete=models.CASCADE, related_name="item_states")
    item_type    = models.CharField(max_length=10, choices=ITEM_TYPES)
    item_id      = models.CharField(max_length=120)
    state        = models.CharField(max_length=20, choices=STATE_CHOICES, default="open")
    snoozed_until = models.DateField(null=True, blank=True)
    updated_at   = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "user_item_states"
        unique_together = [("user", "item_type", "item_id")]

    def __str__(self):
        return f"{self.user_id} / {self.item_type} / {self.item_id} → {self.state}"
