# Generated by Django 6.0.5 on 2026-05-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.PositiveIntegerField(default=2026)),
                ('annual_revenue_zzp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('business_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employment_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hours_per_year', models.PositiveIntegerField(blank=True, null=True)),
                ('years_as_entrepreneur', models.PositiveIntegerField(default=0)),
                ('is_starter', models.BooleanField(default=False)),
                ('has_partner', models.BooleanField(default=False)),
                ('partner_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('children_under_12', models.PositiveIntegerField(default=0)),
                ('rent_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('net_assets_box3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('has_company_bv', models.BooleanField(default=False)),
                ('uses_30pct_ruling', models.BooleanField(default=False)),
                ('pension_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('kia_investments', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('single_client_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tax_profiles',
            },
        ),
    ]
