# Generated by Django 6.0.5 on 2026-05-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=50, unique=True)),
                ('year', models.PositiveIntegerField(default=2026)),
                ('topic', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('user_types', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('condition_summary', models.TextField(blank=True)),
                ('result_type', models.CharField(choices=[('rate', 'Rate'), ('amount', 'Amount'), ('threshold', 'Threshold'), ('risk', 'Risk'), ('deadline', 'Deadline'), ('boolean', 'Boolean')], default='amount', max_length=20)),
                ('result_value', models.FloatField(blank=True, null=True)),
                ('result_unit', models.CharField(blank=True, max_length=20)),
                ('result_formula', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('plain_nl', models.TextField(blank=True)),
                ('plain_en', models.TextField(blank=True)),
                ('plain_fa', models.TextField(blank=True)),
                ('ai_prompt_hint', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('pending_review', 'Pending Review'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('supersedes', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'tax_rules',
                'ordering': ['year', 'rule_id'],
            },
        ),
    ]
