# Generated by Django 6.0.5 on 2026-06-13 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_add_taxrule_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrule',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxrule',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxrule',
            name='shadow_mode',
            field=models.BooleanField(default=False, help_text='Run scenarios against this rule silently before making it live.'),
        ),
        migrations.AddField(
            model_name='taxrule',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='RuleTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('input_data', models.JSONField(help_text="e.g. {'profit': 50000, 'hours': 1400}")),
                ('expected_output', models.JSONField(help_text="e.g. {'eligible': true, 'deduction': 1200}")),
                ('actual_output', models.JSONField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='tax.taxrule')),
            ],
            options={
                'db_table': 'tax_rule_test_cases',
                'ordering': ['rule__rule_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField(default=2026)),
                ('version', models.PositiveIntegerField(default=1)),
                ('items', models.JSONField(default=list, help_text='List of {slug, category, label_nl, label_en, label_fa, priority, description_*} dicts')),
                ('is_active', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tax_checklist_templates',
                'ordering': ['user_type', '-year', '-version'],
                'unique_together': {('user_type', 'year', 'version')},
            },
        ),
    ]
