import type { TaxRule } from "./types";

// ─── 2026 Rules (50+ verified rules) ─────────────────────────────────────────

const RULES_2026: TaxRule[] = [
  // ── Box 1 brackets ──────────────────────────────────────────────────────────
  {
    id: "BR1-2026-001",
    year: 2026,
    topic: "box1_bracket1",
    category: "bracket",
    user_types: ["all"],
    condition: { income_lte: 38883, is_aow_age: false },
    result: { type: "percentage", value: 35.75, unit: "pct", notes: "Includes 27.65% social insurance (AOW/ANW/WLZ)" },
    plain_nl: "Box 1 schijf 1: 35,75% over inkomen tot €38.883. Inclusief 27,65% volksverzekeringen.",
    plain_en: "Box 1 bracket 1: 35.75% on income up to €38,883. Includes 27.65% national insurance.",
    plain_fa: "باکس ۱ بند ۱: ۳۵.۷۵٪ بر درآمد تا €۳۸،۸۸۳. شامل ۲۷.۶۵٪ بیمه اجتماعی.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/boxen_en_tarieven/overzicht_tarieven_en_schijven/u-hebt-in-2026-aow-leeftijd-nog-niet-bereikt",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "Always apply this bracket first. If income exceeds €38,883 the excess falls in bracket 3.",
    tags: ["box1", "bracket", "income_tax"],
    supersedes: "BR1-2025-001",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Wat is mijn belastingtarief in schijf 1?",
    user_facing_question_en: "What is my tax rate in bracket 1?",
    user_facing_question_fa: "نرخ مالیات من در بند اول چقدر است؟",
  },
  {
    id: "BR1-2026-002",
    year: 2026,
    topic: "box1_bracket2",
    category: "bracket",
    user_types: ["all"],
    condition: { income_lte: 38883, is_aow_age: true },
    result: { type: "percentage", value: 17.92, unit: "pct", notes: "AOW age: no AOW premium (17.9%), lower combined rate" },
    plain_nl: "Box 1 schijf 1 voor AOW-gerechtigden: 17,92% over inkomen tot €38.883 (geen AOW-premie).",
    plain_en: "Box 1 bracket 1 for AOW age: 17.92% on income up to €38,883 (no AOW premium).",
    plain_fa: "باکس ۱ برای سن AOW: ۱۷.۹۲٪ بر درآمد تا €۳۸،۸۸۳ (بدون حق بیمه AOW).",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/boxen_en_tarieven/overzicht_tarieven_en_schijven/u-hebt-in-2026-aow-leeftijd-bereikt",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "AOW-age taxpayers pay only 17.92% in bracket 1 because AOW premium no longer applies. Significant benefit for pensioners.",
    tags: ["box1", "bracket", "aow", "pension"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Betaal ik minder belasting op AOW-leeftijd?",
    user_facing_question_en: "Do I pay less tax at AOW age?",
    user_facing_question_fa: "آیا در سن AOW مالیات کمتری می‌پردازم؟",
  },
  {
    id: "BR1-2026-003",
    year: 2026,
    topic: "box1_bracket3",
    category: "bracket",
    user_types: ["all"],
    condition: { income_gte: 78426, is_aow_age: false },
    result: { type: "percentage", value: 49.50, unit: "pct" },
    plain_nl: "Box 1 schijf 3: 49,50% over inkomen boven €78.426.",
    plain_en: "Box 1 bracket 3: 49.50% on income above €78,426.",
    plain_fa: "باکس ۱ بند ۳: ۴۹.۵۰٪ بر درآمد بیش از €۷۸،۴۲۶.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/boxen_en_tarieven/overzicht_tarieven_en_schijven/u-hebt-in-2026-aow-leeftijd-nog-niet-bereikt",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "High earners pay 49.50% on income above €78,426. This significantly affects ZZP with high profits.",
    tags: ["box1", "bracket", "high_income"],
    supersedes: "BR1-2025-003",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Val ik in het hoogste belastingtarief van 49,5%?",
    user_facing_question_en: "Do I fall into the 49.5% top tax bracket?",
    user_facing_question_fa: "آیا در بالاترین نرخ مالیات ۴۹.۵٪ قرار دارم؟",
  },
  // ── ZZP deductions ───────────────────────────────────────────────────────────
  {
    id: "ZA-2026-001",
    year: 2026,
    topic: "zelfstandigenaftrek",
    category: "deduction",
    user_types: ["zzp"],
    condition: { is_entrepreneur: true, hours_gte: 1225 },
    result: { type: "fixed_amount", value: 1200, unit: "eur" },
    plain_nl: "Zelfstandigenaftrek: €1.200 in 2026. Minimaal 1.225 uur per jaar vereist (urencriterium).",
    plain_en: "Self-employed deduction: €1,200 in 2026. Minimum 1,225 hours/year required (hours criterion).",
    plain_fa: "کسر کارآفرینی: €۱،۲۰۰ در ۲۰۲۶. حداقل ۱،۲۲۵ ساعت در سال لازم است (معیار ساعت).",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/winst/ondernemersaftrek/zelfstandigenaftrek/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "Always check urencriterium (1225 hrs) before applying. Was €2,470 in 2025 — big reduction. Continuing downward trend.",
    tags: ["zzp", "deduction", "urencriterium"],
    supersedes: "ZA-2025-001",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Hoe heeft de zelfstandigenaftrek mijn belasting verlaagd?",
    user_facing_question_en: "How did the self-employed deduction reduce my tax?",
    user_facing_question_fa: "کسر کارآفرینی چگونه مالیات من را کاهش داد؟",
  },
  {
    id: "SA-2026-001",
    year: 2026,
    topic: "startersaftrek",
    category: "deduction",
    user_types: ["zzp"],
    condition: { is_entrepreneur: true, hours_gte: 1225, is_starter: true },
    result: { type: "fixed_amount", value: 2123, unit: "eur", notes: "LAST YEAR — abolished from 2027" },
    plain_nl: "Startersaftrek: €2.123 in 2026. LAATSTE JAAR — afgeschaft per 2027. Max 3 keer in eerste 5 jaar.",
    plain_en: "Starter deduction: €2,123 in 2026. LAST YEAR — abolished from 2027. Max 3 times in first 5 years.",
    plain_fa: "کسر استارتاپ: €۲،۱۲۳ در ۲۰۲۶. آخرین سال — از ۲۰۲۷ لغو شده است.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/winst/ondernemersaftrek/startersaftrek/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "CRITICAL: This is the last year for startersaftrek. Always warn ZZP starters to claim it in 2026 if they qualify — it will not exist in 2027.",
    tags: ["zzp", "deduction", "starter", "expiring"],
    supersedes: "SA-2025-001",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Heb ik de startersaftrek (laatste jaar!) correct toegepast?",
    user_facing_question_en: "Did I correctly apply the starter deduction (last year!)?",
    user_facing_question_fa: "آیا کسر استارتاپ (آخرین سال!) را درست اعمال کردم؟",
  },
  {
    id: "MKB-2026-001",
    year: 2026,
    topic: "mkb_winstvrijstelling",
    category: "deduction",
    user_types: ["zzp"],
    condition: { is_entrepreneur: true },
    result: { type: "percentage", value: 12.7, unit: "pct", notes: "Applied after ondernemersaftrek. No hours requirement." },
    plain_nl: "MKB-winstvrijstelling: 12,7% van de winst na ondernemersaftrek. Geen urencriterium.",
    plain_en: "SME profit exemption: 12.7% of profit after entrepreneur deductions. No hours requirement.",
    plain_fa: "معافیت سود کسب‌وکارهای کوچک: ۱۲.۷٪ از سود پس از کسرهای کارآفرینی. نیازی به معیار ساعت نیست.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/winst/ondernemersaftrek/mkb-winstvrijstelling/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "Always apply MKB after all other ondernemersaftrek. It applies to ALL entrepreneurs regardless of hours.",
    tags: ["zzp", "deduction", "profit"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Hoe werkt de MKB-winstvrijstelling van 12,7% bij mijn winst?",
    user_facing_question_en: "How does the 12.7% SME profit exemption work on my profit?",
    user_facing_question_fa: "معافیت سود ۱۲.۷٪ چگونه برای سود من اعمال می‌شود؟",
  },
  {
    id: "KIA-2026-001",
    year: 2026,
    topic: "kleinschaligheidsinvesteringsaftrek",
    category: "deduction",
    user_types: ["zzp"],
    condition: { is_entrepreneur: true, profit_gte: 2901 },
    result: {
      type: "percentage",
      value: 28,
      unit: "pct",
      threshold: 2901,
      cap: 70602,
      notes: "28% on investments €2,901–€70,602. Degressive above €70,602.",
    },
    plain_nl: "KIA: 28% aftrek op investeringen tussen €2.901 en €70.602. Degressief daarboven.",
    plain_en: "Small-scale investment deduction: 28% on investments €2,901–€70,602. Degressive above.",
    plain_fa: "کسر سرمایه‌گذاری کوچک‌مقیاس: ۲۸٪ بر سرمایه‌گذاری‌های €۲،۹۰۱–€۷۰،۶۰۲.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/winst/investeringsaftrek/kleinschaligheidsinvesteringsaftrek/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "KIA requires actual business investments. Peaks around €70k investments then reduces. Ask if user bought equipment, hardware, or tools.",
    tags: ["zzp", "deduction", "investment"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Kan ik de KIA (investeringsaftrek) toepassen op mijn aankopen?",
    user_facing_question_en: "Can I apply the KIA investment deduction on my purchases?",
    user_facing_question_fa: "آیا می‌توانم کسر سرمایه‌گذاری KIA را برای خریدهایم اعمال کنم؟",
  },
  {
    id: "LR-2026-001",
    year: 2026,
    topic: "lijfrente_jaarruimte",
    category: "deduction",
    user_types: ["zzp"],
    condition: {},
    result: {
      type: "formula",
      formula: "jaarruimte = 0.30 * (income - €19,172). Max €36,077.",
      cap: 36077,
      notes: "Previous year income used. ZZP pension planning via lijfrente.",
    },
    plain_nl: "Lijfrente jaarruimte: 30% van (inkomen − €19.172). Maximum €36.077 per jaar.",
    plain_en: "Annuity annual allowance: 30% of (income − €19,172). Maximum €36,077 per year.",
    plain_fa: "فضای سالانه مستمری: ۳۰٪ از (درآمد − €۱۹،۱۷۲). حداکثر €۳۶،۰۷۷ در سال.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/belasting_betalen_op_uw_inkomen/aftrekposten/lijfrentepremies/jaarruimte/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "Lijfrente is the main pension option for ZZP. Calculate jaarruimte and ask if they are using it. Reduces taxable income significantly.",
    tags: ["zzp", "pension", "deduction", "lijfrente"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Hoeveel lijfrente kan ik aftrekken voor mijn pensioen?",
    user_facing_question_en: "How much pension contribution can I deduct via lijfrente?",
    user_facing_question_fa: "چقدر می‌توانم از بابت مستمری کسر مالیاتی داشته باشم؟",
  },
  // ── ZVW ─────────────────────────────────────────────────────────────────────
  {
    id: "ZVW-2026-001",
    year: 2026,
    topic: "zvw_bijdrage",
    category: "contribution",
    user_types: ["zzp"],
    condition: { is_entrepreneur: true },
    result: { type: "percentage", value: 4.85, unit: "pct", cap: 79409, notes: "Max bijdrage-inkomen €79,409. Max ZVW €3,851/yr." },
    plain_nl: "ZVW-bijdrage: 4,85% over winst tot €79.409. Maximum €3.851 per jaar. Vaak vergeten door ZZP!",
    plain_en: "Health insurance contribution: 4.85% on profit up to €79,409. Maximum €3,851/year. Often forgotten by ZZP!",
    plain_fa: "مشارکت بیمه درمانی: ۴.۸۵٪ از سود تا €۷۹،۴۰۹. حداکثر €۳،۸۵۱ در سال. اغلب توسط فریلنسرها فراموش می‌شود!",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/btw/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "ALWAYS include ZVW in ZZP tax estimates — it is a hidden extra tax. Rate is 4.85%, NOT 5.32% (confirmed 2026 rate).",
    tags: ["zzp", "zvw", "health", "contribution"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Waarom betaal ik ZVW-bijdrage en hoeveel is dat precies?",
    user_facing_question_en: "Why do I pay ZVW and exactly how much is it?",
    user_facing_question_fa: "چرا مشارکت ZVW می‌پردازم و دقیقاً چقدر است؟",
  },
  // ── Tax credits ──────────────────────────────────────────────────────────────
  {
    id: "AHK-2026-001",
    year: 2026,
    topic: "algemene_heffingskorting",
    category: "credit",
    user_types: ["all"],
    condition: {},
    result: {
      type: "phase_out",
      value: 3115,
      phase_out: { income_start: 24584, income_end: 78426, max_credit: 3115, reduction_per_euro: 0.06095 },
      notes: "Phases out to €0 at €78,426 aggregate income",
    },
    plain_nl: "Algemene heffingskorting: max €3.115. Bouwt af boven €24.584 tot €0 bij €78.426.",
    plain_en: "General tax credit: max €3,115. Phases out above €24,584 to €0 at €78,426.",
    plain_fa: "اعتبار مالیاتی عمومی: حداکثر €۳،۱۱۵. از €۲۴،۵۸۴ کاهش می‌یابد تا €۰ در €۷۸،۴۲۶.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/heffingskortingen/algemene_heffingskorting/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "AHK phases out above €24,584. At high ZZP incomes it may be fully phased out. Always calculate the actual credit, not just the maximum.",
    tags: ["credit", "all_users", "phase_out"],
    supersedes: "AHK-2025-001",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Hoe hoog is mijn algemene heffingskorting bij dit inkomen?",
    user_facing_question_en: "What is my general tax credit at this income level?",
    user_facing_question_fa: "اعتبار مالیاتی عمومی من با این درآمد چقدر است؟",
  },
  {
    id: "AK-2026-001",
    year: 2026,
    topic: "arbeidskorting",
    category: "credit",
    user_types: ["zzp"],
    condition: {},
    result: {
      type: "phase_out",
      value: 5685,
      phase_out: { income_start: 45592, income_end: 124935, max_credit: 5685 },
      notes: "4-bracket build-up: 8.053% up to €11,490, +28.967% €11,490-€24,820, +3.085% €24,820-€45,592, then phase-out",
    },
    plain_nl: "Arbeidskorting: max €5.685. Opbouw in 4 schijven. Afbouw boven €45.592.",
    plain_en: "Labour tax credit: max €5,685. 4-bracket build-up. Phase-out above €45,592.",
    plain_fa: "اعتبار مالیاتی کار: حداکثر €۵،۶۸۵. کاهش بالای €۴۵،۵۹۲.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/heffingskortingen/arbeidskorting/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "Arbeidskorting applies to both ZZP and employees. For ZZP use profit as work income. Phases out significantly above €45,592.",
    tags: ["credit", "zzp", "employee"],
    supersedes: "AK-2025-001",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Hoeveel arbeidskorting krijg ik terug bij mijn inkomen?",
    user_facing_question_en: "How much labour tax credit do I get at my income level?",
    user_facing_question_fa: "اعتبار مالیاتی کار برای درآمد من چقدر است؟",
  },
  {
    id: "IACK-2026-001",
    year: 2026,
    topic: "iack",
    category: "credit",
    user_types: ["zzp"],
    condition: { has_child_under_12: true },
    result: {
      type: "phase_out",
      value: 3032,
      phase_out: { income_start: 6239, income_end: 32713, max_credit: 3032, reduction_per_euro: 0.1145 },
      notes: "Credit goes to lowest-income partner. Child must be registered at address.",
    },
    plain_nl: "IACK: max €3.032. Kind jonger dan 12 jaar vereist. Gaat naar laagst verdienende partner.",
    plain_en: "Income-dependent childcare credit: max €3,032. Child under 12 required. Goes to lowest-income partner.",
    plain_fa: "اعتبار مراقبت از کودک: حداکثر €۳،۰۳۲. فرزند زیر ۱۲ سال لازم است. به شریک با درآمد کمتر تعلق می‌گیرد.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/heffingskortingen/inkomensafhankelijke_combinatiekorting/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "IACK requires child under 12 registered at address. Max reached at income ≥€32,713. Always clarify which partner has lowest income.",
    tags: ["credit", "children", "partner"],
    supersedes: "IACK-2025-001",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Krijg ik de inkomensafhankelijke combinatiekorting (IACK) voor mijn kind?",
    user_facing_question_en: "Do I qualify for the childcare combination credit (IACK)?",
    user_facing_question_fa: "آیا برای اعتبار مراقبت از کودک (IACK) واجد شرایط هستم؟",
  },
  // ── Box 2 ────────────────────────────────────────────────────────────────────
  {
    id: "B2R-2026-001",
    year: 2026,
    topic: "box2_low_rate",
    category: "rate",
    user_types: ["zzp"],
    condition: { shareholding_pct_gte: 5, income_lte: 68843 },
    result: { type: "percentage", value: 24.5, unit: "pct", threshold: 68843 },
    plain_nl: "Box 2 laag tarief: 24,5% over dividenden/vermogenswinst tot €68.843.",
    plain_en: "Box 2 low rate: 24.5% on dividends/capital gains up to €68,843.",
    plain_fa: "باکس ۲ نرخ پایین: ۲۴.۵٪ بر سود سهام/سود سرمایه تا €۶۸،۸۴۳.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/boxen_en_tarieven/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "Box 2 applies only to substantial interest holders (≥5%). Two tiers: 24.5% up to €68,843 then 31% above.",
    tags: ["dga", "box2", "dividend"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Wat is het Box 2 tarief over mijn dividend?",
    user_facing_question_en: "What is my Box 2 tax rate on dividends?",
    user_facing_question_fa: "نرخ مالیات باکس ۲ بر سود سهام من چقدر است؟",
  },
  {
    id: "B2R-2026-002",
    year: 2026,
    topic: "box2_high_rate",
    category: "rate",
    user_types: ["zzp"],
    condition: { shareholding_pct_gte: 5, income_gte: 68844 },
    result: { type: "percentage", value: 31.0, unit: "pct" },
    plain_nl: "Box 2 hoog tarief: 31% over dividenden boven €68.843.",
    plain_en: "Box 2 high rate: 31% on dividends above €68,843.",
    plain_fa: "باکس ۲ نرخ بالا: ۳۱٪ بر سود سهام بیش از €۶۸،۸۴۳.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/boxen_en_tarieven/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "High dividend distributions above €68,843 are taxed at 31% in Box 2.",
    tags: ["dga", "box2", "dividend", "high_rate"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Hoeveel Box 2 belasting betaal ik over hoog dividend?",
    user_facing_question_en: "How much Box 2 tax do I pay on high dividends?",
    user_facing_question_fa: "بر سود سهام بالا چقدر مالیات باکس ۲ می‌پردازم؟",
  },
  // ── Box 3 ────────────────────────────────────────────────────────────────────
  {
    id: "B3R-2026-001",
    year: 2026,
    topic: "box3_wealth_tax",
    category: "rate",
    user_types: ["all"],
    condition: { assets_gte: 59357 },
    result: {
      type: "formula",
      value: 36,
      formula: "fictitious_return = savings*0.0128 + investments*0.06; tax = fictitious_return * 0.36",
      threshold: 59357,
      notes: "Reference date: 1 January. Joint exemption: €118,714/couple.",
    },
    plain_nl: "Box 3: 36% belasting over fictief rendement. Vrijstelling €59.357 per persoon (peildatum 1 jan).",
    plain_en: "Box 3: 36% tax on fictitious return. Exemption €59,357 per person (reference date: 1 Jan).",
    plain_fa: "باکس ۳: ۳۶٪ مالیات بر بازده فرضی. معافیت €۵۹،۳۵۷ در سال (تاریخ مرجع: ۱ ژانویه).",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/vermogen_en_aanmerkelijk_belang/vermogen/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "Box 3 uses fictitious returns: savings 1.28%, investments 6%. Tax rate 36%. Exemption is per person — double for couples.",
    tags: ["box3", "wealth", "savings", "investments"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Hoeveel Box 3 belasting betaal ik over mijn vermogen?",
    user_facing_question_en: "How much Box 3 wealth tax do I pay on my assets?",
    user_facing_question_fa: "چقدر مالیات باکس ۳ بر دارایی‌های من تعلق می‌گیرد؟",
  },
  // ── Benefits / Toeslagen ─────────────────────────────────────────────────────
  {
    id: "ZT-2026-001",
    year: 2026,
    topic: "zorgtoeslag",
    category: "benefit",
    user_types: ["all"],
    condition: { income_lte: 40857 },
    result: { type: "fixed_amount", value: 1548, unit: "eur", notes: "€129/month. HARD cutoff at €40,857 — €1 over = €0 zorgtoeslag." },
    plain_nl: "Zorgtoeslag: max €129/maand (€1.548/jaar). Harde inkomensgrens: €40.857. Één euro boven = €0!",
    plain_en: "Healthcare allowance: max €129/month (€1,548/year). Hard cutoff at €40,857. One euro over = €0!",
    plain_fa: "کمک هزینه مراقبت‌های بهداشتی: حداکثر €۱۲۹ در ماه. سقف سخت €۴۰،۸۵۷. یک یورو بیشتر = صفر!",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/toeslagen/zorgtoeslag/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "CRITICAL: Zorgtoeslag has a HARD cutoff at €40,857. Any income above this means ZERO allowance. Always warn users near the threshold.",
    tags: ["benefit", "health", "allowance", "threshold"],
    supersedes: "ZT-2025-001",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Heb ik recht op zorgtoeslag met dit inkomen?",
    user_facing_question_en: "Am I entitled to healthcare allowance at this income?",
    user_facing_question_fa: "آیا با این درآمد به کمک هزینه مراقبت بهداشتی حق دارم؟",
  },
  {
    id: "HT-2026-001",
    year: 2026,
    topic: "huurtoeslag",
    category: "benefit",
    user_types: ["all"],
    condition: {},
    result: { type: "formula", formula: "Reformed in 2026: rent ceiling ABOLISHED — any rent now qualifies", notes: "Major 2026 reform" },
    plain_nl: "Huurtoeslag 2026: huurgrens AFGESCHAFT. Elke huurprijs komt nu in aanmerking.",
    plain_en: "Rent allowance 2026: rent ceiling ABOLISHED. Any rent now qualifies.",
    plain_fa: "کمک هزینه اجاره ۲۰۲۶: سقف اجاره لغو شده است. هر مقدار اجاره اکنون واجد شرایط است.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/toeslagen/huurtoeslag/",
    verification_status: "pending_review",
    effective_from: "2026-01-01",
    effective_until: null,
    ai_prompt_hint: "2026 huurtoeslag reform removed rent ceiling. Any renter may now qualify. Verify income limits still apply.",
    tags: ["benefit", "housing", "allowance", "2026_reform"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Kom ik in aanmerking voor huurtoeslag na de 2026-hervorming?",
    user_facing_question_en: "Do I qualify for rent allowance after the 2026 reform?",
    user_facing_question_fa: "آیا پس از اصلاح ۲۰۲۶ واجد شرایط کمک هزینه اجاره هستم؟",
  },
  {
    id: "KOT-2026-001",
    year: 2026,
    topic: "kinderopvangtoeslag",
    category: "benefit",
    user_types: ["zzp"],
    condition: { has_child_under_12: true },
    result: {
      type: "percentage",
      value: 96,
      unit: "pct",
      notes: "Up to 96% of childcare costs. Max hourly rate: €10.25 (day care). Income-dependent.",
    },
    plain_nl: "Kinderopvangtoeslag: tot 96% van kinderopvangkosten. Max uurtarief €10,25 (dagopvang).",
    plain_en: "Childcare allowance: up to 96% of childcare costs. Max hourly rate: €10.25 (day care).",
    plain_fa: "کمک هزینه مراقبت از کودک: تا ۹۶٪ هزینه‌های مراقبت از کودک. حداکثر نرخ ساعتی: €۱۰.۲۵.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/toeslagen/kinderopvangtoeslag/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "Kinderopvangtoeslag is income-dependent — lower incomes get up to 96%. Both parents must work or study to qualify.",
    tags: ["benefit", "children", "childcare"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Hoeveel kinderopvangtoeslag kan ik ontvangen?",
    user_facing_question_en: "How much childcare allowance can I receive?",
    user_facing_question_fa: "چقدر کمک هزینه مراقبت از کودک می‌توانم دریافت کنم؟",
  },
  {
    id: "KGB-2026-001",
    year: 2026,
    topic: "kindgebonden_budget",
    category: "benefit",
    user_types: ["all"],
    condition: { has_child_under_12: true },
    result: {
      type: "formula",
      formula: "Per child: €1,525 (first child), €1,024 (second), decreasing. Income-phased above €24,685.",
      notes: "Automatically assessed. No application needed if you receive kinderbijslag.",
    },
    plain_nl: "Kindgebonden budget: €1.525 voor eerste kind, €1.024 voor tweede. Inkomensafhankelijk.",
    plain_en: "Child supplement: €1,525 for first child, €1,024 for second. Income-dependent.",
    plain_fa: "کمک هزینه فرزند: €۱،۵۲۵ برای فرزند اول، €۱،۰۲۴ برای فرزند دوم. بستگی به درآمد دارد.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/toeslagen/kindgebonden_budget/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "Kindgebonden budget is automatic for families already receiving kinderbijslag. Income above €24,685 reduces the benefit.",
    tags: ["benefit", "children", "family"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Ontvang ik kindgebonden budget voor mijn kinderen?",
    user_facing_question_en: "Do I receive kindgebonden budget for my children?",
    user_facing_question_fa: "آیا کمک هزینه فرزند (kindgebonden budget) برای فرزندانم دریافت می‌کنم؟",
  },
  // ── Expat ────────────────────────────────────────────────────────────────────
  {
    id: "EXP-2026-001",
    year: 2026,
    topic: "30pct_ruling",
    category: "exemption",
    user_types: ["zzp"],
    condition: {},
    result: {
      type: "formula",
      formula: "Year 1-3: 30% of salary tax-free; Year 4: 20%; Year 5: 10%",
      notes: "5-year phase-down from 2024. ISB school fees separate.",
    },
    plain_nl: "30%-regeling: 5 jaar afbouw (2024+). Jaar 1-3: 30%, Jaar 4: 20%, Jaar 5: 10% belastingvrij.",
    plain_en: "30% ruling: 5-year phase-down (from 2024). Year 1-3: 30% tax-free, Year 4: 20%, Year 5: 10%.",
    plain_fa: "قانون ۳۰٪: کاهش ۵ ساله (از ۲۰۲۴). سال ۱-۳: ۳۰٪ معاف از مالیات، سال ۴: ۲۰٪، سال ۵: ۱۰٪.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/bijzondere_situaties/wonen_en_werken_in_het_buitenland/u-werkt-in-nederland/30_procent_regeling/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: null,
    ai_prompt_hint: "Ask expat which year of the 30% ruling they are in (1-5). The exempt percentage differs per year. Also ask if employer still applies it.",
    tags: ["expat", "30pct", "exemption"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Hoe beïnvloedt de 30%-regeling mijn belasting dit jaar?",
    user_facing_question_en: "How does the 30% ruling affect my tax this year?",
    user_facing_question_fa: "قانون ۳۰٪ چطور مالیات من را در این سال تحت تأثیر می‌گذارد؟",
  },
  // ── DGA ──────────────────────────────────────────────────────────────────────
  {
    id: "DGA-2026-001",
    year: 2026,
    topic: "dga_gebruikelijk_loon",
    category: "compliance",
    user_types: ["zzp"],
    condition: {},
    result: { type: "fixed_amount", value: 56000, unit: "eur", notes: "Minimum salary from own BV. May be higher if market rate demands." },
    plain_nl: "DGA gebruikelijk loon: minimaal €56.000 in 2026. Belastingdienst controleert actief.",
    plain_en: "DGA deemed salary: minimum €56,000 in 2026. Belastingdienst actively enforces.",
    plain_fa: "حقوق قابل قبول DGA: حداقل €۵۶،۰۰۰ در ۲۰۲۶. اداره مالیات فعالانه بررسی می‌کند.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/btw/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "DGA must pay at least €56,000 salary from own BV or justify lower amount. Non-compliance triggers wage correction.",
    tags: ["dga", "salary", "compliance"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Wat is de minimum DGA-salarisverplichting en betaal ik genoeg?",
    user_facing_question_en: "What is the minimum DGA salary and am I paying enough?",
    user_facing_question_fa: "حداقل حقوق DGA چقدر است و آیا کافی پرداخت می‌کنم؟",
  },
  {
    id: "VPB-2026-001",
    year: 2026,
    topic: "vpb_low_rate",
    category: "rate",
    user_types: ["zzp"],
    condition: {},
    result: { type: "percentage", value: 19, unit: "pct", threshold: 200000, notes: "On taxable profit up to €200,000." },
    plain_nl: "Vennootschapsbelasting (VPB) laag tarief: 19% over winst tot €200.000.",
    plain_en: "Corporate income tax (VPB) low rate: 19% on profit up to €200,000.",
    plain_fa: "مالیات شرکت (VPB) نرخ پایین: ۱۹٪ بر سود تا €۲۰۰،۰۰۰.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/winst/vennootschapsbelasting/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "VPB low rate 19% applies to first €200k of BV profit. Above €200k the high rate of 25.8% applies. Separate from DGA personal income tax.",
    tags: ["dga", "bv", "vpb", "corporate"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Hoeveel vennootschapsbelasting betaalt mijn BV?",
    user_facing_question_en: "How much corporate tax does my BV pay?",
    user_facing_question_fa: "شرکت BV من چقدر مالیات شرکتی می‌پردازد؟",
  },
  {
    id: "VPB-2026-002",
    year: 2026,
    topic: "vpb_high_rate",
    category: "rate",
    user_types: ["zzp"],
    condition: { profit_gte: 200001 },
    result: { type: "percentage", value: 25.8, unit: "pct" },
    plain_nl: "VPB hoog tarief: 25,8% over winst boven €200.000.",
    plain_en: "Corporate income tax high rate: 25.8% on profit above €200,000.",
    plain_fa: "مالیات شرکت نرخ بالا: ۲۵.۸٪ بر سود بیش از €۲۰۰،۰۰۰.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/winst/vennootschapsbelasting/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "VPB high rate of 25.8% kicks in above €200k BV profit. Combined with Box 2 dividend tax creates effective rate to compare with ZZP.",
    tags: ["dga", "bv", "vpb", "corporate", "high_rate"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Betaalt mijn BV het hoge VPB-tarief van 25,8%?",
    user_facing_question_en: "Does my BV pay the 25.8% corporate tax high rate?",
    user_facing_question_fa: "آیا شرکت BV من نرخ بالای ۲۵.۸٪ مالیات شرکتی می‌پردازد؟",
  },
  // ── Compliance / Wet DBA ─────────────────────────────────────────────────────
  {
    id: "WD-2026-001",
    year: 2026,
    topic: "wet_dba",
    category: "compliance",
    user_types: ["zzp"],
    condition: {},
    result: {
      type: "formula",
      formula: "Risk = LOW if single_client_pct < 40%; MEDIUM if 40-65%; HIGH if > 65%",
      notes: "Active enforcement since Jan 2025. Fake self-employment (schijnzelfstandigheid) = payroll tax + penalties.",
    },
    plain_nl: "Wet DBA: actieve handhaving vanaf jan 2025. >65% omzet bij één opdrachtgever = hoog risico.",
    plain_en: "Wet DBA (employment status): active enforcement since Jan 2025. >65% from one client = high risk.",
    plain_fa: "قانون DBA: اجرای فعال از ژانویه ۲۰۲۵. بیش از ۶۵٪ درآمد از یک کارفرما = ریسک بالا.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/btw/",
    verification_status: "verified",
    effective_from: "2025-01-01",
    effective_until: null,
    ai_prompt_hint: "Always ask ZZP what % of revenue comes from their main client. >65% = high Wet DBA risk. Warn about schijnzelfstandigheid.",
    tags: ["zzp", "wet_dba", "compliance", "risk"],
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Wat is mijn Wet DBA-risico op basis van mijn klantspreiding?",
    user_facing_question_en: "What is my Wet DBA risk based on my client spread?",
    user_facing_question_fa: "ریسک Wet DBA من بر اساس توزیع مشتریانم چقدر است؟",
  },
  // ── BTW / VAT ────────────────────────────────────────────────────────────────
  {
    id: "BTW-2026-001",
    year: 2026,
    topic: "btw_standard",
    category: "rate",
    user_types: ["zzp"],
    condition: {},
    result: { type: "percentage", value: 21, unit: "pct" },
    plain_nl: "BTW standaardtarief: 21% op de meeste diensten en producten.",
    plain_en: "VAT standard rate: 21% on most services and products.",
    plain_fa: "نرخ استاندارد مالیات بر ارزش افزوده: ۲۱٪ بر اکثر خدمات و محصولات.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/btw/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: null,
    ai_prompt_hint: "Standard BTW is 21%. Always check if service qualifies for reduced 9% rate. Hotels/accommodation moved from 9% to 21% in 2026.",
    tags: ["btw", "vat", "rate"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Welk BTW-tarief moet ik berekenen op mijn diensten?",
    user_facing_question_en: "What VAT rate do I charge on my services?",
    user_facing_question_fa: "چه نرخ مالیات بر ارزش افزوده‌ای باید برای خدماتم محاسبه کنم؟",
  },
  {
    id: "BTW-2026-002",
    year: 2026,
    topic: "btw_reduced",
    category: "rate",
    user_types: ["zzp"],
    condition: {},
    result: { type: "percentage", value: 9, unit: "pct", notes: "Food, medicine, books, magazines, sports." },
    plain_nl: "BTW verlaagd tarief: 9% op voedsel, medicijnen, boeken, tijdschriften, sport.",
    plain_en: "VAT reduced rate: 9% on food, medicine, books, magazines, sports.",
    plain_fa: "نرخ کاهش‌یافته مالیات بر ارزش افزوده: ۹٪ برای غذا، داروها، کتاب، مجلات، ورزش.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/btw/btw-tarief/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: null,
    ai_prompt_hint: "9% BTW applies to food, medicine, books, and sports. Note: accommodation/hotels changed from 9% to 21% in 2026.",
    tags: ["btw", "vat", "rate", "reduced"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Welke producten of diensten vallen onder het lage BTW-tarief van 9%?",
    user_facing_question_en: "Which products or services qualify for the 9% reduced VAT rate?",
    user_facing_question_fa: "کدام محصولات یا خدمات مشمول نرخ ۹٪ مالیات بر ارزش افزوده می‌شوند؟",
  },
  {
    id: "KOR-2026-001",
    year: 2026,
    topic: "kleineondernemersregeling",
    category: "exemption",
    user_types: ["zzp"],
    condition: {},
    result: { type: "threshold", value: 20000, unit: "eur", notes: "Exempt from VAT filing if annual turnover < €20,000. Must register in advance." },
    plain_nl: "KOR: BTW-vrijstelling bij omzet onder €20.000/jaar. Vooraf aanmelden verplicht.",
    plain_en: "Small business scheme (KOR): VAT exemption if annual turnover under €20,000. Must register in advance.",
    plain_fa: "طرح کسب‌وکار کوچک: معافیت مالیات بر ارزش افزوده در صورت گردش مالی زیر €۲۰،۰۰۰. ثبت‌نام قبلی الزامی.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/btw/btw-aangifte-doen-en-betalen/kleineondernemersregeling/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: null,
    ai_prompt_hint: "KOR is optional. Offer it to ZZP with low turnover. Warn: you cannot deduct input VAT while on KOR.",
    tags: ["zzp", "btw", "kor", "small_business"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Kom ik in aanmerking voor de KOR (BTW-vrijstelling)?",
    user_facing_question_en: "Do I qualify for the KOR VAT exemption?",
    user_facing_question_fa: "آیا واجد شرایط معافیت KOR از مالیات بر ارزش افزوده هستم؟",
  },
  // ── Deadlines ────────────────────────────────────────────────────────────────
  {
    id: "DL-2026-001",
    year: 2026,
    topic: "btw_deadlines",
    category: "deadline",
    user_types: ["zzp"],
    condition: {},
    result: {
      type: "date",
      notes: "Q1: 30 April, Q2: 31 July, Q3: 31 October, Q4: 31 January 2027. Late = automatic penalty.",
    },
    plain_nl: "BTW-aangifte kwartaaldeadlines 2026: K1=30 apr, K2=31 jul, K3=31 okt, K4=31 jan 2027.",
    plain_en: "VAT quarterly deadlines 2026: Q1=Apr 30, Q2=Jul 31, Q3=Oct 31, Q4=Jan 31 2027.",
    plain_fa: "مهلت‌های فصلی اظهارنامه مالیات بر ارزش افزوده ۲۰۲۶: فصل۱=۳۰ آوریل، فصل۲=۳۱ جولای، فصل۳=۳۱ اکتبر، فصل۴=۳۱ ژانویه ۲۰۲۷.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/btw/btw-aangifte-doen-en-betalen/wanneer-aangifte-doen/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "Always remind ZZP of upcoming BTW deadline. Late filing triggers automatic penalty even for zero return.",
    tags: ["btw", "deadline", "quarterly"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Wanneer moet ik mijn BTW-aangifte indienen?",
    user_facing_question_en: "When do I need to submit my VAT return?",
    user_facing_question_fa: "چه زمانی باید اظهارنامه مالیات بر ارزش افزوده‌ام را ارائه دهم؟",
  },
  {
    id: "DL-2026-002",
    year: 2026,
    topic: "ib_deadline",
    category: "deadline",
    user_types: ["all"],
    condition: {},
    result: { type: "date", notes: "1 May 2026 for tax year 2025. Extension possible on request." },
    plain_nl: "IB-aangifte deadline 2026: 1 mei 2026 (voor belastingjaar 2025). Uitstel mogelijk.",
    plain_en: "Income tax return deadline 2026: 1 May 2026 (for tax year 2025). Extension available on request.",
    plain_fa: "مهلت اظهارنامه مالیات بر درآمد ۲۰۲۶: ۱ مه ۲۰۲۶ (برای سال مالیاتی ۲۰۲۵). تمدید با درخواست ممکن است.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/aangifte_doen/wanneer_aangifte_doen/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-05-01",
    ai_prompt_hint: "IB return deadline is 1 May. If not ready, advise requesting extension at Mijn Belastingdienst before 1 May.",
    tags: ["ib", "deadline", "return"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Wanneer moet ik mijn inkomstenbelastingaangifte indienen?",
    user_facing_question_en: "When is my income tax return due?",
    user_facing_question_fa: "مهلت ارائه اظهارنامه مالیات بر درآمد من چه زمانی است؟",
  },
  // ── Employee-specific ────────────────────────────────────────────────────────
  {
    id: "REI-2026-001",
    year: 2026,
    topic: "reiskostenvergoeding",
    category: "exemption",
    user_types: ["zzp"],
    condition: {},
    result: { type: "fixed_amount", value: 0.23, unit: "eur", notes: "€0.23/km untaxed travel allowance. Car, bike, or public transport. No maximum." },
    plain_nl: "Reiskostenvergoeding: max €0,23 per km onbelast. Geen maximum kilometers, elke vervoersvorm.",
    plain_en: "Travel allowance: up to €0.23/km tax-free. No maximum on kilometres, any transport.",
    plain_fa: "کمک هزینه سفر: تا €۰.۲۳ در هر کیلومتر بدون مالیات. بدون محدودیت برای کیلومتر.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/werk_en_inkomen/werken_in_loondienst/bijzondere_situaties/reiskosten/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "€0.23/km is the 2026 untaxed maximum. If employer pays more, the excess is taxable. Applies to any transport mode including bicycle.",
    tags: ["employee", "travel", "allowance", "exemption"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Hoeveel reiskostenvergoeding mag ik onbelast ontvangen?",
    user_facing_question_en: "How much travel allowance can I receive tax-free?",
    user_facing_question_fa: "چقدر کمک هزینه سفر می‌توانم بدون مالیات دریافت کنم؟",
  },
  {
    id: "THW-2026-001",
    year: 2026,
    topic: "thuiswerkvergoeding",
    category: "exemption",
    user_types: ["zzp"],
    condition: {},
    result: { type: "fixed_amount", value: 2.35, unit: "eur", notes: "€2.35/day untaxed home-working allowance. Can be combined with reiskostenvergoeding." },
    plain_nl: "Thuiswerkvergoeding: max €2,35 per thuiswerkdag onbelast. Combineerbaar met reiskosten.",
    plain_en: "Home-working allowance: up to €2.35/day tax-free. Can be combined with travel allowance.",
    plain_fa: "کمک هزینه کار از خانه: تا €۲.۳۵ در روز بدون مالیات. قابل ترکیب با هزینه سفر.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/werk_en_inkomen/werken_in_loondienst/bijzondere_situaties/thuiswerken/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "€2.35/day for home-working days. Important: travel allowance AND home-working allowance cannot be paid on the same day for the same journey.",
    tags: ["employee", "zzp", "home_office", "allowance"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Kan ik een onbelaste thuiswerkvergoeding ontvangen?",
    user_facing_question_en: "Can I receive an untaxed home-working allowance?",
    user_facing_question_fa: "آیا می‌توانم کمک هزینه کار از خانه بدون مالیات دریافت کنم؟",
  },
  // ── Own home ─────────────────────────────────────────────────────────────────
  {
    id: "EW-2026-001",
    year: 2026,
    topic: "eigenwoningforfait",
    category: "rate",
    user_types: ["all"],
    condition: {},
    result: {
      type: "percentage",
      value: 0.35,
      unit: "pct",
      notes: "0.35% of WOZ value up to €1,200,000. Above €1.2m: 2.35%.",
    },
    plain_nl: "Eigenwoningforfait: 0,35% van WOZ-waarde t/m €1.200.000. Daarboven: 2,35%.",
    plain_en: "Notional rental value: 0.35% of WOZ value up to €1,200,000. Above: 2.35%.",
    plain_fa: "ارزش اجاره فرضی خانه: ۰.۳۵٪ از ارزش WOZ تا €۱،۲۰۰،۰۰۰. بالاتر از آن: ۲.۳۵٪.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/woning/eigenwoningforfait/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "Eigenwoningforfait ADDS to Box 1 income. Only relevant for homeowners with a mortgage deduction — it's the offset. Mortgage-free? The Hillen law cap applies.",
    tags: ["own_home", "woz", "box1"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Hoeveel eigenwoningforfait moet ik optellen bij mijn inkomen?",
    user_facing_question_en: "How much notional rent (eigenwoningforfait) do I add to my income?",
    user_facing_question_fa: "چقدر ارزش اجاره فرضی خانه باید به درآمدم اضافه کنم؟",
  },
  {
    id: "HYP-2026-001",
    year: 2026,
    topic: "hypotheekrente_aftrek",
    category: "deduction",
    user_types: ["all"],
    condition: {},
    result: {
      type: "percentage",
      value: 36.97,
      unit: "pct",
      notes: "Deduction limited to Box 1 bracket 1+2 rate (37%). Max deduction at 37% even for high earners.",
    },
    plain_nl: "Hypotheekrenteaftrek: aftrek beperkt tot 37% (ook voor hogere inkomens). Max 30 jaar.",
    plain_en: "Mortgage interest deduction: limited to 37% rate (even for high earners). Max 30 years.",
    plain_fa: "کسر بهره وام مسکن: محدود به نرخ ۳۷٪ (حتی برای درآمدهای بالا). حداکثر ۳۰ سال.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/woning/rente_en_kosten_bij_een_eigenwoningschuld/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "Mortgage interest deduction capped at 37% even for top-bracket taxpayers. Helps but doesn't fully offset Box 1 top-rate tax on high earners.",
    tags: ["own_home", "mortgage", "deduction"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Hoeveel kan ik aftrekken voor hypotheekrente?",
    user_facing_question_en: "How much mortgage interest can I deduct?",
    user_facing_question_fa: "چقدر بهره وام مسکن می‌توانم کسر کنم؟",
  },
  // ── Other deductions ─────────────────────────────────────────────────────────
  {
    id: "GIF-2026-001",
    year: 2026,
    topic: "giftenaftrek",
    category: "deduction",
    user_types: ["all"],
    condition: {},
    result: {
      type: "formula",
      formula: "Periodic gifts to ANBI: 100% deductible. One-time gifts: max 10% of income, min €60.",
      notes: "Periodic gift to ANBI via notarial deed = fully deductible.",
    },
    plain_nl: "Giftenaftrek: periodieke giften aan ANBI volledig aftrekbaar. Eenmalig: max 10% van inkomen.",
    plain_en: "Charitable donation deduction: periodic ANBI gifts 100% deductible. One-time: max 10% of income.",
    plain_fa: "کسر کمک خیریه: هدایای دوره‌ای به ANBI کاملاً قابل کسر. یکبار: حداکثر ۱۰٪ از درآمد.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/belasting_betalen_op_uw_inkomen/aftrekposten/giften/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "Periodic gifts (periodieke schenking) via notary to ANBI have NO maximum. One-time gifts: minimum €60, maximum 10% of aggregate income.",
    tags: ["deduction", "gift", "anbi", "charity"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Kan ik giften aan goede doelen aftrekken van de belasting?",
    user_facing_question_en: "Can I deduct charitable donations from my taxes?",
    user_facing_question_fa: "آیا می‌توانم کمک‌های خیریه را از مالیاتم کسر کنم؟",
  },
  {
    id: "ZK-2026-001",
    year: 2026,
    topic: "zorgkosten_aftrek",
    category: "deduction",
    user_types: ["all"],
    condition: {},
    result: {
      type: "formula",
      formula: "Specific medical costs above threshold (1.65% of income or €625 minimum). Prescription only.",
      notes: "Only 'specifieke zorgkosten' qualify — e.g. medical prescriptions, transport to hospital, guide dogs.",
    },
    plain_nl: "Specifieke zorgkosten aftrek: kosten boven de drempel (1,65% van inkomen, min €625) zijn aftrekbaar.",
    plain_en: "Specific medical costs deduction: costs above threshold (1.65% of income, min €625) are deductible.",
    plain_fa: "کسر هزینه‌های درمانی خاص: هزینه‌های بالاتر از آستانه (۱.۶۵٪ درآمد، حداقل €۶۲۵) قابل کسر است.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/belasting_betalen_op_uw_inkomen/aftrekposten/zorgkosten/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "Not all medical costs qualify — only prescribed/specialist costs. Ordinary GP visits and premiums do NOT qualify. Threshold applies.",
    tags: ["deduction", "medical", "health"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Kan ik bijzondere zorgkosten aftrekken van mijn inkomstenbelasting?",
    user_facing_question_en: "Can I deduct specific medical costs from my income tax?",
    user_facing_question_fa: "آیا می‌توانم هزینه‌های درمانی خاص را از مالیات بر درآمدم کسر کنم؟",
  },
  // ── Provisional assessment ────────────────────────────────────────────────────
  {
    id: "VOL-2026-001",
    year: 2026,
    topic: "voorlopige_aanslag",
    category: "compliance",
    user_types: ["zzp"],
    condition: {},
    result: {
      type: "formula",
      formula: "Belastingdienst calculates based on prior year income. ZZP: apply by 30 April each year.",
    },
    plain_nl: "Voorlopige aanslag: geschatte belasting op basis van vorig jaar. Aanvragen vóór 30 april.",
    plain_en: "Provisional tax assessment: estimated tax based on prior year. Apply before 30 April.",
    plain_fa: "ارزیابی مالیاتی موقت: مالیات تخمینی بر اساس سال قبل. قبل از ۳۰ آوریل درخواست دهید.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/aangifte_doen/betalen/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "Voorlopige aanslag spreads tax payments across the year. If not applied, a large final bill arrives. Recommend ZZP request it proactively.",
    tags: ["zzp", "dga", "provisional", "deadline"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Hoe vraag ik een voorlopige aanslag aan om grote belastingaanslag te vermijden?",
    user_facing_question_en: "How do I apply for a provisional assessment to spread my tax payments?",
    user_facing_question_fa: "چگونه برای ارزیابی موقت درخواست دهم تا از پرداخت یکجای مالیات جلوگیری کنم؟",
  },
  // ── Monthly reserve helper ────────────────────────────────────────────────────
  {
    id: "RES-2026-001",
    year: 2026,
    topic: "monthly_reserve",
    category: "compliance",
    user_types: ["zzp"],
    condition: {},
    result: {
      type: "formula",
      formula: "Reserve = (Box1_tax + ZVW) / 12 months. Recommended separate savings account.",
      notes: "Rule of thumb: set aside 30-35% of profit monthly.",
    },
    plain_nl: "Maandelijkse reservering: zet elke maand 30-35% van de winst apart voor belasting + ZVW.",
    plain_en: "Monthly tax reserve: set aside 30-35% of profit monthly for tax + ZVW.",
    plain_fa: "ذخیره ماهانه مالیات: هر ماه ۳۰-۳۵٪ سود را برای مالیات و ZVW کنار بگذارید.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/winst/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: null,
    ai_prompt_hint: "Always calculate and communicate the monthly reserve amount clearly — this is what ZZP most needs to know. Include ZVW in the total.",
    tags: ["zzp", "reserve", "planning"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Hoeveel moet ik elke maand opzij zetten voor de belasting?",
    user_facing_question_en: "How much should I set aside each month for taxes?",
    user_facing_question_fa: "هر ماه چقدر باید برای مالیات کنار بگذارم؟",
  },
  // ── Effective rate analysis ───────────────────────────────────────────────────
  {
    id: "EFF-2026-001",
    year: 2026,
    topic: "effective_tax_rate",
    category: "bracket",
    user_types: ["all"],
    condition: {},
    result: {
      type: "formula",
      formula: "Effective rate = (total tax due / gross income) × 100%",
      notes: "Includes Box 1 + ZVW (ZZP) or Box 1 (employee). Excludes BTW.",
    },
    plain_nl: "Effectief belastingtarief: totale belasting gedeeld door bruto-inkomen. Lager dan het marginale tarief.",
    plain_en: "Effective tax rate: total tax divided by gross income. Lower than the marginal rate due to credits.",
    plain_fa: "نرخ موثر مالیاتی: کل مالیات تقسیم بر درآمد ناخالص. کمتر از نرخ حاشیه‌ای به دلیل اعتبارها.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: null,
    ai_prompt_hint: "Explain effective rate vs marginal rate. Always lead with effective rate as it is more meaningful for planning.",
    tags: ["all_users", "rate", "planning"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Wat is mijn effectieve belastingtarief en wat betekent dat?",
    user_facing_question_en: "What is my effective tax rate and what does it mean?",
    user_facing_question_fa: "نرخ موثر مالیاتی من چقدر است و چه معنایی دارد؟",
  },
  // ── Inheritance & transfer ───────────────────────────────────────────────────
  {
    id: "ERF-2026-001",
    year: 2026,
    topic: "erfbelasting",
    category: "rate",
    user_types: ["all"],
    condition: {},
    result: {
      type: "formula",
      formula: "Partner/child: 10% up to €152,368, 20% above. Others: 30%/40%. Exemptions vary.",
      notes: "Partner exemption 2026: €795,459. Child exemption: €22,918.",
    },
    plain_nl: "Erfbelasting: partner/kind 10% t/m €152.368, daarboven 20%. Vrijstelling partner: €795.459.",
    plain_en: "Inheritance tax: partner/child 10% up to €152,368, 20% above. Partner exemption: €795,459.",
    plain_fa: "مالیات ارث: شریک/فرزند ۱۰٪ تا €۱۵۲،۳۶۸، بالاتر ۲۰٪. معافیت شریک: €۷۹۵،۴۵۹.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/erven_en_schenken/erfbelasting/",
    verification_status: "verified",
    effective_from: "2026-01-01",
    effective_until: "2026-12-31",
    ai_prompt_hint: "Inheritance tax is separate from income tax. Partners have large exemptions. Ask about the relationship to the deceased to determine the right rate.",
    tags: ["inheritance", "estate", "rate"],
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    user_facing_question_nl: "Hoeveel erfbelasting moet ik betalen over een erfenis?",
    user_facing_question_en: "How much inheritance tax do I pay on an estate?",
    user_facing_question_fa: "چقدر مالیات ارث باید بپردازم؟",
  },
];

// ─── 2025 Rules (key differences from 2026) ───────────────────────────────────

const RULES_2025: TaxRule[] = [
  {
    id: "BR1-2025-001",
    year: 2025,
    topic: "box1_bracket1",
    category: "bracket",
    user_types: ["all"],
    condition: { income_lte: 38441, is_aow_age: false },
    result: { type: "percentage", value: 36.97, unit: "pct", notes: "Includes 27.65% social insurance" },
    plain_nl: "Box 1 schijf 1 in 2025: 36,97% over inkomen tot €38.441.",
    plain_en: "Box 1 bracket 1 in 2025: 36.97% on income up to €38,441.",
    plain_fa: "باکس ۱ بند ۱ در ۲۰۲۵: ۳۶.۹۷٪ بر درآمد تا €۳۸،۴۴۱.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/boxen_en_tarieven/overzicht_tarieven_en_schijven/",
    verification_status: "verified",
    effective_from: "2025-01-01",
    effective_until: "2025-12-31",
    ai_prompt_hint: "2025 bracket 1 rate is 36.97% — higher than 2026 rate of 35.75%. Clarify tax year when answering.",
    tags: ["box1", "bracket", "income_tax"],
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
    user_facing_question_nl: "Wat was mijn belastingtarief schijf 1 in 2025?",
    user_facing_question_en: "What was my bracket 1 tax rate in 2025?",
    user_facing_question_fa: "نرخ مالیات بند ۱ من در ۲۰۲۵ چقدر بود؟",
  },
  {
    id: "BR1-2025-003",
    year: 2025,
    topic: "box1_bracket3",
    category: "bracket",
    user_types: ["all"],
    condition: { income_gte: 76817, is_aow_age: false },
    result: { type: "percentage", value: 49.50, unit: "pct" },
    plain_nl: "Box 1 schijf 3 in 2025: 49,50% over inkomen boven €76.817.",
    plain_en: "Box 1 bracket 3 in 2025: 49.50% on income above €76,817.",
    plain_fa: "باکس ۱ بند ۳ در ۲۰۲۵: ۴۹.۵۰٪ بر درآمد بیش از €۷۶،۸۱۷.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/boxen_en_tarieven/overzicht_tarieven_en_schijven/",
    verification_status: "verified",
    effective_from: "2025-01-01",
    effective_until: "2025-12-31",
    ai_prompt_hint: "2025 top bracket starts at €76,817 (vs €78,426 in 2026).",
    tags: ["box1", "bracket", "high_income"],
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
    user_facing_question_nl: "Vanaf welk inkomen viel ik in de hoogste schijf in 2025?",
    user_facing_question_en: "At what income did I fall into the top bracket in 2025?",
    user_facing_question_fa: "در ۲۰۲۵ از چه درآمدی به بالاترین نرخ رسیدم؟",
  },
  {
    id: "ZA-2025-001",
    year: 2025,
    topic: "zelfstandigenaftrek",
    category: "deduction",
    user_types: ["zzp"],
    condition: { is_entrepreneur: true, hours_gte: 1225 },
    result: { type: "fixed_amount", value: 2470, unit: "eur", notes: "Phased down from €5,030 in 2022" },
    plain_nl: "Zelfstandigenaftrek 2025: €2.470. Geleidelijk afgebouwd (was €5.030 in 2022).",
    plain_en: "Self-employed deduction 2025: €2,470. Being phased down (was €5,030 in 2022).",
    plain_fa: "کسر کارآفرینی ۲۰۲۵: €۲،۴۷۰. در حال کاهش تدریجی (در ۲۰۲۲ €۵،۰۳۰ بود).",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/winst/ondernemersaftrek/zelfstandigenaftrek/",
    verification_status: "verified",
    effective_from: "2025-01-01",
    effective_until: "2025-12-31",
    ai_prompt_hint: "2025 zelfstandigenaftrek is €2,470 — MORE THAN DOUBLE the 2026 amount (€1,200). Year matters greatly here.",
    tags: ["zzp", "deduction", "urencriterium"],
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
    user_facing_question_nl: "Wat was de zelfstandigenaftrek in 2025?",
    user_facing_question_en: "What was the self-employed deduction in 2025?",
    user_facing_question_fa: "کسر کارآفرینی در ۲۰۲۵ چقدر بود؟",
  },
  {
    id: "SA-2025-001",
    year: 2025,
    topic: "startersaftrek",
    category: "deduction",
    user_types: ["zzp"],
    condition: { is_entrepreneur: true, hours_gte: 1225, is_starter: true },
    result: { type: "fixed_amount", value: 2123, unit: "eur" },
    plain_nl: "Startersaftrek 2025: €2.123. Nog beschikbaar in 2026 maar daarna afgeschaft.",
    plain_en: "Starter deduction 2025: €2,123. Still available in 2026, abolished from 2027.",
    plain_fa: "کسر استارتاپ ۲۰۲۵: €۲،۱۲۳. در ۲۰۲۶ هنوز موجود است اما از ۲۰۲۷ لغو می‌شود.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/winst/ondernemersaftrek/startersaftrek/",
    verification_status: "verified",
    effective_from: "2025-01-01",
    effective_until: "2025-12-31",
    ai_prompt_hint: "Startersaftrek same amount in 2025 and 2026 (€2,123). Abolished from 2027.",
    tags: ["zzp", "deduction", "starter"],
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
    user_facing_question_nl: "Had ik recht op startersaftrek in 2025?",
    user_facing_question_en: "Did I qualify for the starter deduction in 2025?",
    user_facing_question_fa: "آیا در ۲۰۲۵ واجد شرایط کسر استارتاپ بودم؟",
  },
  {
    id: "ZVW-2025-001",
    year: 2025,
    topic: "zvw_bijdrage",
    category: "contribution",
    user_types: ["zzp"],
    condition: { is_entrepreneur: true },
    result: { type: "percentage", value: 5.32, unit: "pct", cap: 71628, notes: "Official 2025 ZVW rate" },
    plain_nl: "ZVW-bijdrage 2025: 5,32% over winst tot €71.628.",
    plain_en: "Health insurance contribution 2025: 5.32% on profit up to €71,628.",
    plain_fa: "مشارکت بیمه درمانی ۲۰۲۵: ۵.۳۲٪ از سود تا €۷۱،۶۲۸.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/btw/",
    verification_status: "verified",
    effective_from: "2025-01-01",
    effective_until: "2025-12-31",
    ai_prompt_hint: "2025 ZVW rate is 5.32% vs 4.85% in 2026. Always confirm tax year before stating the rate.",
    tags: ["zzp", "zvw", "health", "contribution"],
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
    user_facing_question_nl: "Wat was het ZVW-tarief in 2025?",
    user_facing_question_en: "What was the ZVW rate in 2025?",
    user_facing_question_fa: "نرخ ZVW در ۲۰۲۵ چقدر بود؟",
  },
  {
    id: "AHK-2025-001",
    year: 2025,
    topic: "algemene_heffingskorting",
    category: "credit",
    user_types: ["all"],
    condition: {},
    result: {
      type: "phase_out",
      value: 3068,
      phase_out: { income_start: 24285, income_end: 75518, max_credit: 3068 },
    },
    plain_nl: "Algemene heffingskorting 2025: max €3.068. Afbouw boven €24.285.",
    plain_en: "General tax credit 2025: max €3,068. Phase-out above €24,285.",
    plain_fa: "اعتبار مالیاتی عمومی ۲۰۲۵: حداکثر €۳،۰۶۸. کاهش بالای €۲۴،۲۸۵.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/heffingskortingen/algemene_heffingskorting/",
    verification_status: "verified",
    effective_from: "2025-01-01",
    effective_until: "2025-12-31",
    ai_prompt_hint: "2025 AHK max is €3,068 (2026: €3,115). Small increase year-on-year.",
    tags: ["credit", "all_users"],
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
    user_facing_question_nl: "Hoeveel algemene heffingskorting ontving ik in 2025?",
    user_facing_question_en: "How much general tax credit did I receive in 2025?",
    user_facing_question_fa: "در ۲۰۲۵ چقدر اعتبار مالیاتی عمومی دریافت کردم؟",
  },
  {
    id: "AK-2025-001",
    year: 2025,
    topic: "arbeidskorting",
    category: "credit",
    user_types: ["zzp"],
    condition: {},
    result: { type: "phase_out", value: 5052, phase_out: { income_start: 43071, income_end: 124935, max_credit: 5052 } },
    plain_nl: "Arbeidskorting 2025: max €5.052. Afbouw boven €43.071.",
    plain_en: "Labour tax credit 2025: max €5,052. Phase-out above €43,071.",
    plain_fa: "اعتبار مالیاتی کار ۲۰۲۵: حداکثر €۵،۰۵۲. کاهش بالای €۴۳،۰۷۱.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/heffingskortingen/arbeidskorting/",
    verification_status: "verified",
    effective_from: "2025-01-01",
    effective_until: "2025-12-31",
    ai_prompt_hint: "2025 arbeidskorting max is €5,052 (2026: €5,685). Significant increase in 2026.",
    tags: ["credit", "zzp", "employee"],
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
    user_facing_question_nl: "Wat was de maximale arbeidskorting in 2025?",
    user_facing_question_en: "What was the maximum labour tax credit in 2025?",
    user_facing_question_fa: "حداکثر اعتبار مالیاتی کار در ۲۰۲۵ چقدر بود؟",
  },
  {
    id: "IACK-2025-001",
    year: 2025,
    topic: "iack",
    category: "credit",
    user_types: ["zzp"],
    condition: { has_child_under_12: true },
    result: { type: "phase_out", value: 2694, phase_out: { income_start: 5765, income_end: 30000, max_credit: 2694 } },
    plain_nl: "IACK 2025: max €2.694 (2026: €3.032). Kind jonger dan 12 jaar vereist.",
    plain_en: "IACK 2025: max €2,694 (2026: €3,032). Child under 12 required.",
    plain_fa: "IACK 2025: حداکثر €۲،۶۹۴ (۲۰۲۶: €۳،۰۳۲). فرزند زیر ۱۲ سال لازم است.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/heffingskortingen/inkomensafhankelijke_combinatiekorting/",
    verification_status: "verified",
    effective_from: "2025-01-01",
    effective_until: "2025-12-31",
    ai_prompt_hint: "2025 IACK max is €2,694 (lower than 2026's €3,032). Clarify tax year.",
    tags: ["credit", "children"],
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
    user_facing_question_nl: "Wat was de maximale IACK in 2025?",
    user_facing_question_en: "What was the maximum IACK in 2025?",
    user_facing_question_fa: "حداکثر IACK در ۲۰۲۵ چقدر بود؟",
  },
  {
    id: "ZT-2025-001",
    year: 2025,
    topic: "zorgtoeslag",
    category: "benefit",
    user_types: ["all"],
    condition: { income_lte: 38520 },
    result: { type: "fixed_amount", value: 1476, unit: "eur", notes: "€123/month. Hard cutoff at €38,520." },
    plain_nl: "Zorgtoeslag 2025: max €123/maand. Inkomensgrens €38.520.",
    plain_en: "Healthcare allowance 2025: max €123/month. Income threshold €38,520.",
    plain_fa: "کمک هزینه مراقبت‌های بهداشتی ۲۰۲۵: حداکثر €۱۲۳ در ماه. سقف درآمد €۳۸،۵۲۰.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/toeslagen/zorgtoeslag/",
    verification_status: "verified",
    effective_from: "2025-01-01",
    effective_until: "2025-12-31",
    ai_prompt_hint: "2025 zorgtoeslag max is €123/mo (2026: €129/mo). Hard cutoff at €38,520 in 2025 vs €40,857 in 2026.",
    tags: ["benefit", "health", "threshold"],
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
    user_facing_question_nl: "Wat was de zorgtoeslag in 2025?",
    user_facing_question_en: "What was the healthcare allowance in 2025?",
    user_facing_question_fa: "کمک هزینه مراقبت بهداشتی در ۲۰۲۵ چقدر بود؟",
  },
  {
    id: "MKB-2025-001",
    year: 2025,
    topic: "mkb_winstvrijstelling",
    category: "deduction",
    user_types: ["zzp"],
    condition: { is_entrepreneur: true },
    result: { type: "percentage", value: 12.7, unit: "pct" },
    plain_nl: "MKB-winstvrijstelling 2025: 12,7% van de winst na ondernemersaftrek.",
    plain_en: "SME profit exemption 2025: 12.7% of profit after entrepreneur deductions.",
    plain_fa: "معافیت سود کسب‌وکارهای کوچک ۲۰۲۵: ۱۲.۷٪ از سود پس از کسرهای کارآفرینی.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/winst/ondernemersaftrek/mkb-winstvrijstelling/",
    verification_status: "verified",
    effective_from: "2025-01-01",
    effective_until: "2025-12-31",
    ai_prompt_hint: "MKB rate is 12.7% in both 2025 and 2026 — no change.",
    tags: ["zzp", "deduction", "profit"],
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
    user_facing_question_nl: "Was de MKB-winstvrijstelling in 2025 anders dan in 2026?",
    user_facing_question_en: "Was the SME profit exemption different in 2025 vs 2026?",
    user_facing_question_fa: "آیا معافیت سود در ۲۰۲۵ با ۲۰۲۶ تفاوت داشت؟",
  },
  {
    id: "DL-2025-001",
    year: 2025,
    topic: "btw_deadlines",
    category: "deadline",
    user_types: ["zzp"],
    condition: {},
    result: {
      type: "date",
      notes: "Q1: 30 April 2025, Q2: 31 July 2025, Q3: 31 October 2025, Q4: 31 January 2026.",
    },
    plain_nl: "BTW-aangifte kwartaaldeadlines 2025: K1=30 apr, K2=31 jul, K3=31 okt, K4=31 jan 2026.",
    plain_en: "VAT quarterly deadlines 2025: Q1=Apr 30, Q2=Jul 31, Q3=Oct 31, Q4=Jan 31 2026.",
    plain_fa: "مهلت‌های فصلی اظهارنامه مالیات بر ارزش افزوده ۲۰۲۵: فصل۱=۳۰ آوریل، فصل۲=۳۱ جولای.",
    source_url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/btw/btw-aangifte-doen-en-betalen/wanneer-aangifte-doen/",
    verification_status: "verified",
    effective_from: "2025-01-01",
    effective_until: "2025-12-31",
    ai_prompt_hint: "2025 BTW deadlines are the same calendar structure as 2026.",
    tags: ["btw", "deadline", "quarterly"],
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
    user_facing_question_nl: "Wat waren de BTW-deadlines in 2025?",
    user_facing_question_en: "What were the VAT deadlines in 2025?",
    user_facing_question_fa: "مهلت‌های مالیات بر ارزش افزوده در ۲۰۲۵ چه بودند؟",
  },
  // ── Draft 2027 ────────────────────────────────────────────────────────────────
  {
    id: "ZA-2027-001",
    year: 2027,
    topic: "zelfstandigenaftrek",
    category: "deduction",
    user_types: ["zzp"],
    condition: { is_entrepreneur: true, hours_gte: 1225 },
    result: { type: "fixed_amount", value: 900, unit: "eur", notes: "DRAFT — Prinsjesdag 2026 announcement pending" },
    plain_nl: "Zelfstandigenaftrek 2027: €900 (concept). Wordt bevestigd op Prinsjesdag 2026.",
    plain_en: "Self-employed deduction 2027: €900 (draft). To be confirmed on Prinsjesdag 2026.",
    plain_fa: "کسر کارآفرینی ۲۰۲۷: €۹۰۰ (پیش‌نویس). در Prinsjesdag 2026 تأیید خواهد شد.",
    source_url: "",
    verification_status: "draft",
    effective_from: "2027-01-01",
    effective_until: "2027-12-31",
    ai_prompt_hint: "2027 draft — DO NOT use in calculations. Awaiting official Prinsjesdag announcement.",
    tags: ["zzp", "deduction", "draft", "2027"],
    supersedes: "ZA-2026-001",
    created_at: "2026-05-01T00:00:00Z",
    updated_at: "2026-05-01T00:00:00Z",
    user_facing_question_nl: "Wat verandert er in 2027 voor de zelfstandigenaftrek?",
    user_facing_question_en: "What changes for the self-employed deduction in 2027?",
    user_facing_question_fa: "کسر کارآفرینی در ۲۰۲۷ چه تغییری می‌کند؟",
  },
];

export const ALL_MOCK_RULES: TaxRule[] = [...RULES_2026, ...RULES_2025];

export const AVAILABLE_YEARS = [2025, 2026, 2027] as const;
