# Generated by Django 6.0.5 on 2026-06-07 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountantClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('client_type', models.CharField(choices=[('employee', 'Employee'), ('zzp', 'ZZP / Freelancer'), ('expat', 'Expat'), ('dga', 'DGA / Director'), ('other', 'Other / Unknown')], default='other', max_length=20)),
                ('preferred_language', models.CharField(choices=[('nl', 'Nederlands'), ('en', 'English'), ('fa', 'فارسی')], default='nl', max_length=5)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('collecting', 'Collecting documents'), ('in_review', 'In review'), ('ready', 'Ready to file'), ('completed', 'Completed'), ('archived', 'Archived')], default='invited', max_length=20)),
                ('tax_year', models.PositiveIntegerField(default=2026)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accountant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_clients', to=settings.AUTH_USER_MODEL)),
                ('client_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_client_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('request_type', models.CharField(choices=[('identity', 'Identity'), ('income', 'Income'), ('expense', 'Expense'), ('bank', 'Bank statement'), ('payroll', 'Payroll'), ('mortgage', 'Mortgage'), ('pension', 'Pension / lijfrente'), ('investment', 'Investment'), ('property', 'Property / WOZ'), ('business', 'Business'), ('vat', 'VAT / BTW'), ('contract', 'Contract'), ('other', 'Other')], default='other', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('uploaded', 'Uploaded'), ('partially_uploaded', 'Partially uploaded'), ('needs_review', 'Needs review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waived', 'Waived')], default='open', max_length=30)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_by', models.CharField(choices=[('accountant', 'Accountant'), ('rule_engine', 'Rule engine'), ('ai_suggestion', 'AI suggestion')], default='accountant', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='portal.accountantclientprofile')),
            ],
            options={
                'db_table': 'portal_document_requests',
                'ordering': ['required', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='portal/documents/%Y/%m/')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('document_type', models.CharField(choices=[('unknown', 'Unknown'), ('receipt', 'Receipt'), ('invoice', 'Invoice'), ('jaaropgave', 'Jaaropgave'), ('payslip', 'Payslip'), ('bank_statement', 'Bank statement'), ('mortgage_statement', 'Mortgage statement'), ('pension_statement', 'Pension statement'), ('kvk_extract', 'KVK extract'), ('vat_report', 'VAT / BTW report'), ('contract', 'Contract'), ('id_document', 'ID document'), ('tax_letter', 'Tax letter'), ('other', 'Other')], default='unknown', max_length=30)),
                ('processing_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('extracted', 'Extracted'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='uploaded', max_length=20)),
                ('extracted_json', models.JSONField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='portal.accountantclientprofile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_uploads', to=settings.AUTH_USER_MODEL)),
                ('document_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='portal.documentrequest')),
            ],
            options={
                'db_table': 'portal_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.PositiveIntegerField(default=2026)),
                ('engagement_type', models.CharField(choices=[('income_tax', 'Income Tax Return'), ('vat', 'VAT / BTW'), ('annual_accounts', 'Annual Accounts'), ('payroll', 'Payroll'), ('advisory', 'Advisory')], default='income_tax', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('collecting', 'Collecting'), ('waiting_client', 'Waiting for client'), ('needs_review', 'Needs review'), ('ready_to_file', 'Ready to file'), ('filed', 'Filed'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='draft', max_length=20)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('readiness_score', models.PositiveIntegerField(default=0)),
                ('missing_items_count', models.PositiveIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('summary_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accountant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements_as_accountant', to=settings.AUTH_USER_MODEL)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='portal.accountantclientprofile')),
            ],
            options={
                'db_table': 'portal_engagements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=50)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accountant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_accountant_logs', to=settings.AUTH_USER_MODEL)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('client_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='portal.accountantclientprofile')),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='portal.taxengagement')),
            ],
            options={
                'db_table': 'portal_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(choices=[('salary', 'Salary'), ('zzp_revenue', 'ZZP revenue'), ('dividend', 'Dividend'), ('benefit', 'Benefit / uitkering'), ('foreign_income', 'Foreign income'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_withheld', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('review_status', models.CharField(choices=[('candidate', 'Candidate (not yet approved)'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('manual', 'Manually entered')], default='candidate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_items', to='portal.accountantclientprofile')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_income', to='portal.clientdocument')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_items', to='portal.taxengagement')),
            ],
            options={
                'db_table': 'portal_extracted_income',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_category', models.CharField(choices=[('laptop', 'Laptop / computer'), ('phone', 'Phone'), ('internet', 'Internet'), ('software', 'Software / subscriptions'), ('travel', 'Travel'), ('car', 'Car'), ('office', 'Office'), ('home_office', 'Home office'), ('training', 'Training / courses'), ('accountant', 'Accountant / bookkeeping'), ('marketing', 'Marketing'), ('insurance', 'Insurance'), ('pension', 'Pension / lijfrente'), ('equipment', 'Equipment'), ('meal', 'Meal / entertainment'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount_gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_net', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('business_use_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('expense_date', models.DateField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('review_status', models.CharField(choices=[('candidate', 'Candidate (not yet approved)'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('manual', 'Manually entered')], default='candidate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='portal.accountantclientprofile')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_expenses', to='portal.clientdocument')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='portal.taxengagement')),
            ],
            options={
                'db_table': 'portal_extracted_expenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='portal.taxengagement'),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='portal.taxengagement'),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('waiting_client', 'Waiting for client'), ('uploaded', 'Uploaded'), ('needs_review', 'Needs review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waived', 'Waived')], default='todo', max_length=20)),
                ('source', models.CharField(choices=[('template', 'Template'), ('accountant', 'Accountant'), ('rule_engine', 'Rule engine'), ('ai', 'AI suggestion')], default='template', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('stable_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='portal.accountantclientprofile')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='portal.taxengagement')),
            ],
            options={
                'db_table': 'portal_checklist_items',
                'ordering': ['-required', 'priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountantAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('action_type', models.CharField(choices=[('request_document', 'Request document'), ('review_document', 'Review document'), ('check_deduction', 'Check deduction'), ('send_reminder', 'Send reminder'), ('review_risk', 'Review risk'), ('approve_extraction', 'Approve extraction'), ('prepare_filing', 'Prepare filing')], default='request_document', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('source', models.CharField(choices=[('rule_engine', 'Rule engine'), ('ai', 'AI'), ('manual', 'Manual')], default='rule_engine', max_length=20)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('stable_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='portal.accountantclientprofile')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='portal.taxengagement')),
            ],
            options={
                'db_table': 'portal_accountant_actions',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
