# Generated by Django 6.0.5 on 2026-06-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial_portal_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='stable_key',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
