# Generated by Django 6.0.5 on 2026-06-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_add_stable_key_to_document_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='user_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='user_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
