# Generated by Django 6.0.5 on 2026-06-12 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_add_user_title_note_to_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='portal.accountantclientprofile')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='portal.taxengagement')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('document_request', 'Document request'), ('deadline', 'Deadline reminder'), ('status_update', 'Status update'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('channel', models.CharField(choices=[('push', 'Push notification'), ('email', 'Email'), ('in_app', 'In-app')], default='in_app', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='portal.accountantclientprofile')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='portal.taxengagement')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_reminder_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
