# Generated by Django 6.0.5 on 2026-06-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_add_reminder_log_portal_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='retention_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
