# Generated by Django 6.0.5 on 2026-06-13 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_gdpr_document_retention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kvk_number', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('subscription_plan', models.CharField(choices=[('free', 'Free'), ('professional', 'Professional'), ('firm', 'Firm')], default='free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'portal_firms',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='taxengagement',
            name='accountant_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxengagement',
            name='readiness_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxengagement',
            name='ready_to_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxengagement',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements', to='portal.firm'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('tax_year', models.PositiveIntegerField(default=2026)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('client_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_received', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation', to='portal.taxengagement')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadinessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('doc_score', models.FloatField()),
                ('checklist_score', models.FloatField()),
                ('verification_score', models.FloatField()),
                ('accountant_review_score', models.FloatField()),
                ('ready_to_file', models.BooleanField(default=False)),
                ('trigger_event', models.CharField(blank=True, max_length=100)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_snapshots', to='portal.taxengagement')),
            ],
            options={
                'db_table': 'portal_readiness_snapshots',
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('raw_value', models.TextField(blank=True, help_text='As OCR read it')),
                ('normalized_value', models.TextField(blank=True, help_text="Cleaned value (e.g., '48500.00')")),
                ('confidence', models.FloatField(default=0.0)),
                ('bounding_box', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('accepted', 'Accepted'), ('corrected', 'Corrected'), ('rejected', 'Rejected')], default='candidate', max_length=20)),
                ('corrected_value', models.TextField(blank=True, help_text="Accountant's correction")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_fields', to='portal.clientdocument')),
            ],
            options={
                'db_table': 'portal_extracted_fields',
                'ordering': ['document', 'field_name'],
                'unique_together': {('document', 'field_name')},
            },
        ),
    ]
