# Generated by Django 5.2.15 on 2026-07-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_zzp_only_hard_pivot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='processing_status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('extracted', 'Extracted'), ('extraction_failed', 'Extraction failed'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='uploaded', max_length=20),
        ),
    ]
