# Generated by Django 6.0.5 on 2026-05-30 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_intake_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxYearSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.PositiveIntegerField()),
                ('profile_snapshot', models.JSONField()),
                ('calc_snapshot', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(choices=[('auto', 'Auto-captured'), ('ib_guide', 'IB Guide completion'), ('simulation', 'Simulation completion'), ('admin', 'Admin-triggered'), ('user', 'User-saved')], default='auto', max_length=20)),
                ('is_final', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tax_year_snapshots',
                'ordering': ['-tax_year'],
                'unique_together': {('user', 'tax_year', 'is_final')},
            },
        ),
    ]
