# Generated by Django 6.0.5 on 2026-06-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_emailcapture_taxreminder_user_tax_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountantprofile',
            name='designation',
            field=models.CharField(blank=True, choices=[('RB', 'Register Belastingadviseur (RB)'), ('AA', 'Accountant-Administratieconsulent (AA)'), ('RA', 'Registeraccountant (RA)'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='accountantprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Admin-verified accountant credential'),
        ),
        migrations.AddField(
            model_name='accountantprofile',
            name='kvk_number',
            field=models.CharField(blank=True, help_text='8-digit KvK registration number', max_length=20),
        ),
        migrations.AddField(
            model_name='accountantprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='accountantprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('accountant', 'Accountant'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
