# Generated by Django 6.0.5 on 2026-05-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.PositiveIntegerField(default=2026)),
                ('input_snapshot', models.JSONField()),
                ('result', models.JSONField()),
                ('total_tax_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('monthly_reserve', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
