# Generated by Django 6.0.5 on 2026-06-12 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0004_add_reminder_log_portal_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountantReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('revenue', 'Revenue entry'), ('expense', 'Expense entry'), ('hours', 'Hours entry'), ('mileage', 'Mileage entry')], max_length=20)),
                ('entry_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('needs_more_info', 'Needs more information')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zzp_review_events', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zzp_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zzp_accountant_review_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZZPExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('laptop', 'Laptop / computer'), ('phone', 'Phone'), ('internet', 'Internet'), ('software', 'Software / subscriptions'), ('travel', 'Travel'), ('car', 'Car'), ('office', 'Office supplies'), ('home_office', 'Home office'), ('training', 'Training / courses'), ('accountant', 'Accountant / bookkeeping'), ('marketing', 'Marketing'), ('insurance', 'Insurance'), ('pension', 'Pension / lijfrente'), ('equipment', 'Equipment / tools'), ('meal', 'Meal / entertainment'), ('other', 'Other')], default='other', max_length=30)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('amount_gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_rate', models.PositiveSmallIntegerField(choices=[(0, '0%'), (9, '9%'), (21, '21%')], default=21)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('business_use_pct', models.PositiveSmallIntegerField(default=100)),
                ('deductible_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='zzp/receipts/%Y/%m/')),
                ('year', models.PositiveSmallIntegerField(default=2026)),
                ('quarter', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zzp_expenses', to='portal.taxengagement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zzp_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zzp_expense_entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZZPHoursEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('year', models.PositiveSmallIntegerField(default=2026)),
                ('week', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zzp_hours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zzp_hours_entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ZZPMileageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('km', models.DecimalField(decimal_places=1, max_digits=8)),
                ('purpose', models.CharField(max_length=255)),
                ('is_business', models.BooleanField(default=True)),
                ('year', models.PositiveSmallIntegerField(default=2026)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zzp_mileage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zzp_mileage_entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ZZPRevenueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('amount_excl_vat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_rate', models.PositiveSmallIntegerField(choices=[(0, '0% (exempt / KOR)'), (9, '9% (reduced)'), (21, '21% (standard)')], default=21)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_incl_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('partial', 'Partially paid')], default='unpaid', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='zzp/invoices/%Y/%m/')),
                ('year', models.PositiveSmallIntegerField(default=2026)),
                ('quarter', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zzp_revenue', to='portal.taxengagement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zzp_revenue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zzp_revenue_entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
