/**
 * Generates a printable IB return summary and triggers the browser print dialog.
 * No external dependencies — uses a hidden window with styled HTML.
 */

export interface IBAnswers {
  "1a"?: string | null;   // Salary
  "1b"?: string | null;   // Other work income
  "1c"?: string | null;   // Business profit (ZZP/DGA)
  "1d"?: string | null;   // Startersaftrek (yes/no)
  "1e"?: string | null;   // Zelfstandigenaftrek (yes/no)
  "2a"?: string | null;   // Box 2 dividend
  "3a"?: string | null;   // Savings
  "3b"?: string | null;   // Investments
  "8a"?: string | null;   // Mortgage interest
  recommendations?: string[];
  user_type?: string;
  year?: number;
}

type Lang = "nl" | "en" | "fa";

const LABELS: Record<string, Record<Lang, string>> = {
  "1a": { nl: "Loon / salaris (bruto)",           en: "Salary / wages (gross)",          fa: "حقوق / دستمزد (ناخالص)" },
  "1b": { nl: "Andere inkomsten uit arbeid",       en: "Other work income",                fa: "سایر درآمدهای کاری" },
  "1c": { nl: "Winst uit onderneming",             en: "Business profit",                  fa: "سود کسب‌وکار" },
  "1d": { nl: "Startersaftrek",                    en: "Starter's deduction",              fa: "کسر کارآفرین تازه‌کار" },
  "1e": { nl: "Zelfstandigenaftrek",               en: "Self-employed deduction",          fa: "کسر خوداشتغالی" },
  "2a": { nl: "Dividend uit aanmerkelijk belang",  en: "Dividend (substantial interest)",  fa: "سود سهام" },
  "3a": { nl: "Spaargeld / banktegoeden",          en: "Savings / bank balance",           fa: "پس‌انداز / موجودی بانکی" },
  "3b": { nl: "Beleggingen",                       en: "Investments",                      fa: "سرمایه‌گذاری‌ها" },
  "8a": { nl: "Hypotheekrenteaftrek",              en: "Mortgage interest deduction",      fa: "کسر بهره وام مسکن" },
};

const TITLES: Record<Lang, { title: string; subtitle: string; generated: string; disclaimer: string; type: string; recommendations: string; recSubtitle: string }> = {
  nl: {
    title: "IB Aangifte Overzicht",
    subtitle: "Inkomstenbelasting",
    generated: "Gegenereerd door TaxWijs op",
    disclaimer: "Dit overzicht is uitsluitend informatief. Raadpleeg een belastingadviseur voor uw definitieve aangifte.",
    type: "Type",
    recommendations: "Belasting besparen — persoonlijke tips",
    recSubtitle: "Op basis van uw antwoorden heeft de belastingassistent de volgende aanbevelingen:",
  },
  en: {
    title: "IB Return Summary",
    subtitle: "Inkomstenbelasting (Income Tax)",
    generated: "Generated by TaxWijs on",
    disclaimer: "This summary is for informational purposes only. Consult a tax advisor for your final return.",
    type: "Type",
    recommendations: "Tax Optimization — Personalized Tips",
    recSubtitle: "Based on your answers, the tax assistant recommends the following actions:",
  },
  fa: {
    title: "خلاصه اظهارنامه مالیاتی",
    subtitle: "مالیات بر درآمد هلند",
    generated: "تولید شده توسط TaxWijs در",
    disclaimer: "این خلاصه صرفاً جهت اطلاع است. برای اظهارنامه نهایی با مشاور مالیاتی مشورت کنید.",
    type: "نوع",
    recommendations: "بهینه‌سازی مالیات — نکات شخصی‌سازی‌شده",
    recSubtitle: "بر اساس پاسخ‌های شما، دستیار مالیاتی موارد زیر را توصیه می‌کند:",
  },
};

function fmt(val: string | null | undefined, fieldCode: string): string {
  if (!val || val === "null") return "—";
  if (val === "yes") return "✓";
  if (val === "no") return "✗";
  const n = parseFloat(val);
  if (!isNaN(n) && ["1a","1b","1c","2a","3a","3b","8a"].includes(fieldCode)) {
    return `€ ${n.toLocaleString("nl-NL")}`;
  }
  return val;
}

export function printIBReport(answers: IBAnswers, lang: Lang = "nl"): void {
  const tx = TITLES[lang] ?? TITLES.en;
  const year = answers.year ?? 2025;
  const userType = (answers.user_type ?? "").toUpperCase();
  const date = new Date().toLocaleDateString(lang === "nl" ? "nl-NL" : lang === "fa" ? "fa-IR" : "en-GB");
  const dir = lang === "fa" ? "rtl" : "ltr";

  const rows = Object.entries(LABELS)
    .filter(([code]) => {
      const val = answers[code as keyof IBAnswers];
      return val && String(val) !== "null" && String(val) !== "0";
    })
    .map(([code, labels]) => {
      const label = labels[lang] ?? labels.en;
      const raw = answers[code as keyof IBAnswers];
      const value = fmt(typeof raw === "number" ? String(raw) : Array.isArray(raw) ? raw.join(", ") : raw, code);
      return `<tr><td class="code">${code}</td><td class="label">${label}</td><td class="value">${value}</td></tr>`;
    })
    .join("");

  const html = `<!DOCTYPE html>
<html lang="${lang}" dir="${dir}">
<head>
  <meta charset="UTF-8">
  <title>TaxWijs — ${tx.title} ${year}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap');
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Inter', sans-serif; font-size: 14px; color: #1a1a1a; background: #fff; padding: 48px; max-width: 720px; margin: 0 auto; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 36px; padding-bottom: 20px; border-bottom: 2px solid #2d5a27; }
    .brand { font-size: 22px; font-weight: 600; color: #2d5a27; letter-spacing: -0.02em; }
    .meta { text-align: end; font-size: 12px; color: #666; }
    .meta strong { display: block; font-size: 16px; font-weight: 600; color: #1a1a1a; margin-bottom: 4px; }
    .badge { display: inline-block; padding: 3px 10px; background: #e8f5e3; color: #2d5a27; border-radius: 999px; font-size: 12px; font-weight: 600; margin-top: 8px; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    th { text-align: start; font-size: 12px; font-weight: 600; color: #666; text-transform: uppercase; letter-spacing: 0.06em; padding: 10px 12px; background: #f5f5f5; }
    td { padding: 11px 12px; border-bottom: 1px solid #e8e8e8; vertical-align: middle; }
    td.code { font-family: monospace; font-size: 12px; color: #888; width: 40px; }
    td.label { color: #333; }
    td.value { font-weight: 600; color: #1a1a1a; text-align: end; white-space: nowrap; }
    .rec-section { margin-top: 32px; }
    .rec-title { font-size: 13px; font-weight: 600; color: #2d5a27; margin-bottom: 4px; }
    .rec-subtitle { font-size: 12px; color: #666; margin-bottom: 14px; }
    .rec-list { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 10px; }
    .rec-item { display: flex; gap: 10px; align-items: flex-start; padding: 12px 14px; background: #f0f7ed; border-left: 3px solid #2d5a27; border-radius: 4px; font-size: 13px; line-height: 1.55; color: #1a1a1a; }
    .rec-num { font-size: 12px; font-weight: 700; color: #2d5a27; min-width: 20px; padding-top: 1px; }
    .disclaimer { margin-top: 32px; padding: 14px 16px; background: #fffbe6; border: 1px solid #ffe066; border-radius: 6px; font-size: 12px; color: #7a6000; line-height: 1.5; }
    .footer { margin-top: 24px; font-size: 12px; color: #aaa; text-align: center; }
    @media print {
      body { padding: 0; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="brand">TaxWijs</div>
      <div style="font-size:12px;color:#666;margin-top:4px">${tx.subtitle}</div>
    </div>
    <div class="meta">
      <strong>${tx.title} ${year}</strong>
      ${tx.generated} ${date}
      ${userType ? `<div class="badge">${userType}</div>` : ""}
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th></th>
        <th>Omschrijving</th>
        <th style="text-align:end">Bedrag / Waarde</th>
      </tr>
    </thead>
    <tbody>
      ${rows || '<tr><td colspan="3" style="color:#aaa;text-align:center;padding:24px">No answers recorded</td></tr>'}
    </tbody>
  </table>

  ${
    answers.recommendations && answers.recommendations.length > 0
      ? `<div class="rec-section">
    <div class="rec-title">${tx.recommendations}</div>
    <div class="rec-subtitle">${tx.recSubtitle}</div>
    <ul class="rec-list">
      ${answers.recommendations.map((tip, i) => `<li class="rec-item"><span class="rec-num">${i + 1}</span><span>${tip}</span></li>`).join("")}
    </ul>
  </div>`
      : ""
  }

  <div class="disclaimer">${tx.disclaimer}</div>

  <div class="footer">taxwijs.nl · ${year}</div>

  <script>window.onload = function() { window.print(); }<\/script>
</body>
</html>`;

  const win = window.open("", "_blank", "width=800,height=900");
  if (!win) {
    // Fallback: generate a data URL if popup was blocked
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `taxwijs-ib-${year}.html`;
    a.click();
    URL.revokeObjectURL(url);
    return;
  }
  win.document.write(html);
  win.document.close();
}
